ministryofjustice/hmpps-education-and-work-plan-api

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/HmppsEducationAndWorkPlanApi.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/HmppsEducationAndWorkPlanApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/health/HealthInfo.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/health/VersionOutputter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/Placeholder.kt
src/main/resources/logback-spring.xml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/health/HealthInfoTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/integration/health/HealthCheckTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/integration/health/InfoTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/hmppseducationandworkplanapi/Placeholder.kt

This PR renames the base package from `hmppseducationandworkplanapi` to `educationandworkplanapi` because the `hmpps` prefix is redundant because its in the parent package.
Also added sub packages for `app` and `domain`

Renamed base package; added sub packages for app and domain

---

build.gradle.kts
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/TimelineTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/service/TimelineServiceTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/TimeLineBuilder.kt

This PR fixes the test fixtures.
The problem was that `java-test-fixtures` is dependent on the `jar` task at build time (to access the `main` classes from the Spring Boot plain jar).
However, `dps-gradle-spring-boot` disables the `jar` task because it creates the Spring Boot plain jar, which in turn means there are 2 jars in the lib folder once the Spring Boot fat jar has been created. This means the `Dockerfile` has indeterminate behaviour as to which jar file to copies into the container.
This PR fixes the problem by enabling the `jar` task (to get `java-test-fixtures` working again); and then deleting the plain jar (and the test fixtures jar) before the Spring Boot fat jar is created.

Enable jar task to fix test-fixtures

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/Goal.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/Step.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/GoalTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalServiceTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/GoalBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/StepBuilder.kt

Following on from @nathanrussell-moj-digital's [PR](https://github.com/ministryofjustice/hmpps-education-and-work-plan-api/pull/5) to add a basic service for Timeline events, this PR follows the same pattern and introduces a service for Goals.

Add basic GoalService along with builders and tests

---

build.gradle.kts
helm_deploy/hmpps-education-and-work-plan-api/values.yaml
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/resources/application-integration-test.yml
src/integrationTest/resources/application-test.yml
src/main/resources/application.yml

This PR adds the JPA and flyway dependencies, and sets up the helm gubbins to provide the database secrets from the environment.
At the moment I've wired in h2 as the database for the integration tests as it was easier. As we start building out the functionality we can consider whether we'd be better off with h2 or postgres in docker (testcontainers)

Wire in database

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalServiceTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/CommonBuilders.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/Placeholder.kt

This PR adds the prison number as an argument to the domain Goal service and persistence adapter methods for `saveGoal`
The need for this has come out of the work I am currently doing re: creating the Goal JPA entities and writing the implementation to actually save to the database - without the prison number we cannot fulfil the RDBMS relationship of a Goal to its 'parent' ActionPlan

Added the prisonNumber to the domain Goal service and persistence adapter methods

---

build.gradle.kts
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/JwtConfig.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/JwtConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/AuthAwareTokenConverter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/ResourceServerConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/UserContext.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/UserContextFilter.kt

This PR copies the basic spring security config from activities-api
This is needed as part of the JPA work (because we need the user principal for the createdBy etc fields), but I didnt want to bring all the spring security stuff into that PR because that PR is big enough already!
Its a bare bones spring security config - we can configure it to our needs once we get into the detail of the controllers etc

Setup spring security

---

README.md
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/ResourceServerConfiguration.kt

This PR updates the web security config to allow the openapi spec document (static document) to be served without any authentication token.
To demonstrate the current problem, go to: https://hmpps-education-and-work-plan-api-dev.hmpps.service.justice.gov.uk/swagger-ui/index.html?configUrl=/v3/api-docs

Fix security config so that openapi doc is served to unauthenticated requests

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/GoalEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/StepEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/StepEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/StepResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/Goal.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/Step.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/TargetDateRange.kt
src/main/resources/db/migration/V2023.07.10.0001__date_field_changes_.sql
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/StepEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/GoalResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/StepResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/StepEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/StepEntityBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/GoalBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/StepBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/CreateGoalRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/GoalResponseBuilder.kt

This PR introduces the following changes:
- `reviewDate` is now optional throughout.
- `targetDateRange` has been added to the domain, entity and DB.
- `targetDate` has been removed from the domain and all builders. It remains in the entity and DB but is effectively ignored. This is in case the business change their mind and revert back to `targetDate` (which is unlikely, but possible given the indecision over it in the first place).
Needs to be merged at the same time as https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/pull/36

RR-81 - Date related changes in DB, entity and domain

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/GoalEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/MappingExclusions.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/GoalResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/Goal.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/GoalEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/GoalResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/GoalTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/GoalEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/GoalEntityBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/GoalBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/ActionPlanResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/GoalResponseAssert.kt

This PR updates the relevant mappers so that the created by and updated by display names are returned out through the API response

RR-106 - Map and return display names in GoalResponse

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanEntity.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml

As per the ACs in RR-106, the goals should be ordered chronologically (oldest first) and it makes sense to do this in the API.

RR-161 - Return the goals in chronological order

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/GoalEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/Goal.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/GoalCategory.kt
src/main/resources/db/migration/V2023.07.27.0001__remove_goal_category.sql
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/GoalEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/GoalResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/GoalTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/GoalEntityBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/GoalBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/CreateGoalRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/GoalResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/GoalResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/StepResponseBuilder.kt

A tidy up of the API, prior to adding a new endpoint to edit a Goal:
* Remove the redundant `category` field from Goal
* Set the reference fields to UUID types

RR-3 - Remove Goal category

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/CommonBuilders.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/UpdateGoalRequestBuilder.kt

This PR implements the controller method signature to implement the new API defined in the swagger spec to Update A Goal
The controller method does not yet implement the behaviour, but does implement the endpoint signature and security, so basic integration tests have been added 👍 
Subsequent PRs will start to build upon this ...

RR-3 (1) - Implement controller signature for new API endpoint to update a Goal

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ErrorAttributesConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GlobalExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt
src/main/resources/messages.properties
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/ErrorResponseAssert.kt

This PR adds request body validation to the Update Goal API (and also the Create Goal API, as it was not quite right)
Configured the GlobalExceptionHandler to process the correct exceptions and to process the ErrorAttributes instance into an ErrorResponse

RR-3 (2) - Configure GlobalExceptionHandler to handle validation errors

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/Goal.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/GoalTest.kt

This PR updates the domain `Goal` class to enforce that a `Goal`s `Step`s are correctly ordered based on their `sequenceNumber` ; and that when adding a new `Step` it is added in the correct position in the ordered list of `Step`s based on it's `sequenceNumber`

RR-3 - Updated goal steps to ensure and enforce sequence number ordering

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/GoalResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/StepResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/GoalResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/StepResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/CreateGoalRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/CreateStepRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/UpdateGoalRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/UpdateStepRequestBuilder.kt

This PR makes a change to the OpenAPI / swagger spec that @mattwills-moj-digital updated last week (sorry Matt! 😁 )
Matt's PR and change to the API had separate objects for `CreateGoalRequest` and `UpdateGoalRequest`, but they both shared a common `StepRequest` object to represent the steps in the goal.
Because it was a shared object it meant the `stepReference` field had to be optional, because when creating a Step the client (our UI) doesn't know the step reference (the UI is not responsible for generating it). But when updating a Step (via updating the Goal) the client does know the step reference and needs to include it in the request so we know what Step to retrieve and update.
So we made the `stepReference` optional - not 100% ideal, but it served its purpose at the time ....
As …

RR-3 - Refactor CreateStepRequest and UpdateStepRequest in API

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/StepResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/StepResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/UpdateStepRequestBuilder.kt

This PR fixes the `UpdateStepRequest` API object to support adding new steps as part of the Update Goal flow.
New steps in this context are those without a reference; so this PR corrects the API so that the `stepReference` field of `UpdateStepRequest` is optional. The mapper then generates a new reference UUID if one is not present on the request object.

RR-32 - Fix Update Goal to support adding new steps

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/ApplicationInsightsConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/TelemetryService.kt

Provide TelemetryClient bean in the same way that all the other HMPPS apps do
My previous PR didnt work, in that it could not find a TelemetryClient bean at runtime, so perhaps I didnt undersyand how it works (despite my fine kdoc 😁 )
This PR uses the same ApplicationInsightsConfiguration class that all the other HMPPS do, complete the with kdoc that (IMHO) doesnt really make much sense!

RR-237 - Provide TelemetryClient bean 

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryService.kt

Getting the previously set custom dimensions to use in `trackEvent` method calls was not working , so for the time being it can wait. We'll look at it again another time if it proves to be an issue/requirement

RR-237 - Removing trying to get custom dimensions

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanTest.kt
src/integrationTest/resources/db/h2/V2023.08.15.0001__add_action_plan_fields.sql
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/ActionPlan.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/Goal.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/GoalStatus.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/Step.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/StepStatus.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/TargetDateRange.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/ActionPlanService.kt
src/main/resources/db/postgres/V2023.08.15.0001__add_action_plan_fields.sql
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanEntityTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/ActionPlanEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/ActionPlanResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanEntityBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/ActionPlanBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/ActionPlanResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/CreateActionPlanRequestBuilder.kt

This PR adds a new enum `reviewDateCategory` to `ActionPlan`. This is to capture the possible options that the user can choose from in relation to setting the review "date", as shown here:
This PR includes all the changes from the API to the DB.
Note that this PR will be merged into https://github.com/ministryofjustice/hmpps-education-and-work-plan-api/pull/56, which in turn will be merged into https://github.com/ministryofjustice/hmpps-education-and-work-plan-api/pull/55 for the overall _Create Action Plan_ endpoint. Because of this, I haven't bumped the version of the swagger spec and I'm able to use the same DB migration scripts, since they haven't been deployed yet.

RR-230 Add ReviewDateCategory to Action Plan

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanTest.kt
src/integrationTest/resources/db/h2/V2023.08.15.0001__add_action_plan_fields.sql
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/ActionPlanResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/ActionPlan.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/ActionPlanService.kt
src/main/resources/db/postgres/V2023.08.15.0001__add_action_plan_fields.sql
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanEntityTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/ActionPlanEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/ActionPlanResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanEntityBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/ActionPlanBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/ActionPlanResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/ActionPlanResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/CreateActionPlanRequestBuilder.kt

I've decided to remove `reviewDateCategory` as I think we're in danger of making this more complicated than it needs to be! As things stand, I reckon it will be unlikely we'll need to redisplay the previously chosen option (e.g. "3 months") when editing an Action Plan (and if we do then we can always add it back into the API, but let's not try and second guess that now).
My understanding is that the radio buttons to choose 3/6/12 months are just a convenient to set the `reviewDate` quickly, so the user doesn't have to manually type it in each time. In either case, we're still setting the `reviewDate` and I don't think we will care what the user previously choose when we come to edit it, perhaps months later. We might choose to default one of the radio buttons, but that's different to …

RR-230 - Remove review date category

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/GoalResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/CreateGoalRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/GoalResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/UpdateGoalRequestBuilder.kt

This PR updates the swagger spec to include the prison ID in createGoal and updateGoal requests; and the response object for a Goal

RR-236 - swagger spec to include prison ID on createGoal, updateGoal and getGoal

---

domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/ActionPlanSummary.kt
domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/ActionPlanPersistenceAdapter.kt
domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/ActionPlanService.kt
domain/goal/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/ActionPlanSummaryBuilder.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ActionPlanServiceTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaActionPlanPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanSummaryProjection.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/ActionPlanEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/repository/ActionPlanRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaActionPlanPersistenceAdapterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/ActionPlanEntityMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/CommonBuilders.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanSummaryProjectionBuilder.kt

This PR adds the required changes to repository, service and mapper classes to retrieve a list of `ActionPlanSummary` instances.
Instead of retrieving the whole `ActionPlanEntity` and then returning a subset of the fields, I'm using a JPA class based projection - `ActionPlanSummaryProjection` (which I think is the right name given it's not a JPA entity!).

RR-274 - Retrieve Action Plan Summaries - repository, service and mapper

---

domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/dto/CreateGoalDto.kt
domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/dto/UpdateGoalDto.kt
domain/goal/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/dto/CreateGoalDtoBuilder.kt
domain/goal/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/dto/UpdateGoalDtoBuilder.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/GoalEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/GoalEntityMapper.kt
src/main/resources/db/migration/V2023.09.06.0001__add_prison_id_fields_to_goal.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/GoalEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/GoalEntityMapperUpdateEntityFromDtoTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/GoalResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/GoalEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/GoalEntityBuilder.kt

This PR adds the columns `createdAtPrison` and `updatedAtPrison` to the `GoalEntity` and database table.
It also maps the values that are passed into relevant the create/update REST API endpoints through to the entity.
A subsequent PR will return these values in the `GoalResponse` object.

RR-282 - Add Prison ID columns and map from create/update requests

---

build.gradle.kts
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryServiceTest.kt

This PR adds the Update Goal event to the `TelemtryService` and wires it into the controller for the update goal request.
I've added awaitility, and added assertions that the events were sent in the relevant integration tests.
Strictly speaking there is no need for awaitility at this point as it is all synchronous, but my next PR will introduce an AOP aspect and an async `Future` or similar to send the events, rather than coupling it into the controller.

RR-308 - App Insights event for Updating a Goal

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryServiceTest.kt

This PR tracks the number of characters used in the `notes` field of  `Goal` in App Insights events for both Create and Update.
We already have code that tracks the `Goal` Create and Update events, so this PR is simply a case of adding the field to the event's custom dimensions 👍

RR-305 - Track a Goal's notes character length in App Insights

---

domain/timeline/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/TimelineEvent.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetTimelineTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/TimelineController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/TimelineEventResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/TimelineResourceMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/TimelineEventResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/TimelineResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/TimelineEventEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/TimelineEventResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/TimelineEventResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/TimelineResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/TimelineResponseBuilder.kt

This PR adds an endpoint to retrieve a list of Timeline "events" in chronological order, detailed in the swagger spec:
A number of additional assertions have been added to existing integration tests (e.g. `CreateGoalTest`) to ensure the expected events are created. Also, a new integration test (`GetTimelineTest`) has been added to test the new endpoint in isolation.

RR-321 GET timeline endpoint

---

domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalPersistenceAdapter.kt
domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalService.kt
domain/goal/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalServiceTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalsTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanSummariesTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetTimelineTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaActionPlanPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt
src/main/resources/messages.properties
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapterTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/ActionPlanResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/CreateGoalsRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/GoalResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/StepResourceAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/TimelineResponseAssert.kt

This PR refactors the `create-goal` API to `create-goals` to be able to support creating 1 or more goals in a single request.
It's a pretty big PR, and theres been quite a lot of refactoring along the way. The largest refactoring was the `CreateGoalsIntegrationTest` where the test now exclusively uses REST API calls to setup data and assert state (previously it used database access via repository classes, and we were getting into a confusing mess with transactions !)

RR-152 - Refactor `create-goal` API to `create-goals`

---

domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/Step.kt
domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/dto/CreateStepDto.kt
domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/dto/UpdateStepDto.kt
domain/goal/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/StepBuilder.kt
domain/goal/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/dto/CreateStepDtoBuilder.kt
domain/goal/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/dto/UpdateStepDtoBuilder.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalsTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/StepEntity.kt
src/main/resources/db/migration/V2023.09.26.0001__alter_step_target_date_range_nullable.sql
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/StepEntityBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/CreateStepRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/StepResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/UpdateStepRequestBuilder.kt

This PR makes a `Step`s `targetDateRange` optional, ready for us to remove it from the UI

RR-349 - Make step targetDateRange optional

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryEventType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryService.kt

This PR makes a minor refactoring to the enum `TelemetryEventType` so that it is responsible for generating the custom dimensions map, rather than doing it in `TelemetryService`
Previously the enum `TelemetryEventType` knew about and was responsible for the App Insights customEvent name (the `value` field), but the `TelemetryService` knew about how to generate the custom dimensions for each event type. This felt wrong.
This PR adds a field to the enum `TelemetryEventType` which is a function that returns the custom dimensions specific for that event type. It feels right, in that the enum now knows about everything it needs in order to send the App Insights telemetry event. It knows about the customEvent name, and also the map of custom dimensions 👍

RR-307 - TelemetryEventType now responsible for the events custom dimensions

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

This PR configures the helm deployment so that the API service pod is automatically shutdown and restarted in `dev` and `preprod` outside of working hours in order to save some AWS running costs.
The API on `dev` and `preprod` has been configured to automatically
* shutdown at 9pm UTC Monday to Friday
* startup at 6:30am UTC Monday to Friday
Therefore the UI in `dev` and `preprod` will be unavailable overnight between 9pm and 6:30 the next morning; and all weekend.

RR-299 - Automatic shutdown/startup for dev and preprod

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/TempRepositoryTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/FutureWorkInterestsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InPrisonInterestsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InductionEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InductionNotFoundException.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PersonalSkillsAndInterestsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PreviousQualificationsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PreviousTrainingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PreviousWorkExperiencesEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/WorkOnReleaseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/repository/InductionRepository.kt
src/main/resources/db/migration/V2023.10.17.0001__add_induction_related_tables.sql

This PR introduces quite a few DB tables and JPA entities to represent a CIAG Induction.
Note that I've created an `InductionRepository` and a corresponding integration test locally to make sure I can save and retrieve an `InductionEntity`. I'll add test data builders in a subsequent PR, but I'll save the integration test until it's hooked up with the REST API.

RR-422 - Induction related tables and entities

---

src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/CreateCiagInductionRequestBuilder.kt

This PR adds the GET Induction endpoint to our swagger spec. To avoid breaking the CIAG UI, it's as close as possible to the existing version in the CIAG API: https://ciag-induction-api-dev.hmpps.service.justice.gov.uk/swagger-ui/index.html#/ciag-resource-controller/getCIAGProfileForOffenderId
The structure (e.g. names of fields) are identical, but I've pointed out any diversions away from the current spec in the comments.
Here's how the endpoint looks in our Swagger, alongside the recently added create Induction endpoint:

RR-429 - GET Induction Swagger spec

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/InPrisonInterestsResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PersonalSkillsAndInterestsResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PreviousWorkExperiencesResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsAndTrainingResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/CreateCiagInductionRequestMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/InPrisonInterestsResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PersonalSkillsAndInterestsResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PreviousWorkExperiencesResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsAndTrainingResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/CreateCiagInductionRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/EducationAndQualificationsRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousWorkRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PrisonWorkAndEducationRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/SkillsAndInterestsRequestBuilder.kt

PR to add the swagger spec for the update Induction endpoint.
As part of this change, I've prefixed the existing create Induction related request objects with `Request...`, hence the large diff, but really only the swagger spec needs reviewing.

RR-432 - Update Induction swagger spec

---

domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdateFutureWorkInterestsDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdateInPrisonInterestsDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdateInductionDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdatePersonalSkillsAndInterestsDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdatePreviousQualificationsDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdatePreviousTrainingDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdatePreviousWorkExperiencesDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdateWorkOnReleaseDto.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/FutureWorkInterestsResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PreviousWorkExperiencesResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/FutureWorkInterestsResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PreviousWorkExperiencesResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/EducationAndQualificationsRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousWorkRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PrisonWorkAndEducationRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/SkillsAndInterestsRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/UpdateCiagInductionRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/WorkInterestsBuilder.kt

As the title suggests, this PR makes some corrections to the swagger spec and also adds the required test data builders for the new Update Induction API model objects. It also adds the required Update DTOs.
This is a precursor before I create a separate PR to add the mappers for converting the update model objects to the new Update DTOs.

RR-431 - Corrections to swagger spec and update request builders

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/FutureWorkInterestsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InPrisonInterestsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PersonalSkillsAndInterestsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousQualificationsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousTrainingEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousWorkExperiencesEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/WorkOnReleaseEntityMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/FutureWorkInterestsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InPrisonInterestsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PersonalSkillsAndInterestsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousQualificationsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousTrainingEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousWorkExperiencesEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/WorkOnReleaseEntityMapperTest.kt

A precursor before adding `fromUpdateDtoToEntity` methods.

RR-431 - Rename mapper methods

---

domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/FutureWorkInterests.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/FutureWorkInterestsResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/InPrisonInterestsResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PersonalSkillsAndInterestsResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PreviousWorkExperiencesResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsAndTrainingResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/UpdateCiagInductionRequestMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/WorkOnReleaseResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/FutureWorkInterestsResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/InPrisonInterestsResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PersonalSkillsAndInterestsResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PreviousWorkExperiencesResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsAndTrainingResourceMapperTest.kt

This PR introduces the mappers to convert from the Update Induction API request objects to the equivalent Update DTO ones. It's essentially a copy & paste of the Create Induction mappers, except with the addition of the `id` field.

RR-431 - Update Induction API model to DTO mappers

---

domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/FutureWorkInterestsBuilder.kt
domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/FutureWorkInterestsDtoBuilder.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/FutureWorkInterestsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/FutureWorkInterestsEntityMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/FutureWorkInterestsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdateFutureWorkInterestsEntityMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/FutureWorkInterestsEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/FutureWorkInterestsEntityBuilder.kt

This PR adds the necessary `MapStruct` implementation for updating an existing `FutureWorkInterestsEntity` from an incoming `UpdateFutureWorkInterestsDto`.
I've deliberately only done this for future work interests because a) this has already changed 8 files and b) I want to make sure we're happy with this approach.

RR-431 - Mappers for updating an induction's future work interests

---

domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/InPrisonInterestsDtoBuilder.kt
domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/PersonalSkillsAndInterestsDtoBuilder.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InPrisonInterestsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PersonalSkillsAndInterestsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InPrisonInterestsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PersonalSkillsAndInterestsEntityMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InPrisonInterestsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PersonalSkillsAndInterestsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdateFutureWorkInterestsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdateInPrisonInterestsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdatePersonalSkillsAndInterestsEntityMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InPrisonInterestsEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InPrisonInterestsEntityBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PersonalSkillsAndInterestsEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PersonalSkillsAndInterestsEntityBuilder.kt

This PR introduces the required `MapStruct` methods to update `PersonalSkillsAndInterests` and `InPrisonInterests`. Since both of the respective mappers use two internal "child" mappers, it made sense to do these at the same time. 
Unfortunately it's resulted in a lot of repetitive code and long test methods, which I'll see if I can do something about once I've finished the rest of the mapping.

RR-431 - Mappers for updating SkillsAndInterests and InPrisonInterests

---

domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionPersistenceAdapter.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionService.kt
domain/induction/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionServiceTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/InductionController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/InPrisonInterestsResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PreviousWorkExperiencesResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/ApiResponseAssertions.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/CiagInductionResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/EducationAndQualificationsResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousWorkResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PrisonWorkAndEducationResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/SkillsAndInterestsResponseBuilder.kt

This PR adds the required controller and service for updating an Induction. It also adds an integration test, which currently ensures that each "child" object is updated when a value to update it is provided (i.e. I am not yet testing updates with null child objects).

RR-433 - Update induction controller & service, plus initial integration test

---

domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionEventService.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionService.kt
domain/induction/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionServiceTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetTimelineTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/DomainConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaActionPlanPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncInductionEventService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaActionPlanPersistenceAdapterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncInductionEventServiceTest.kt

This PR ensures that `INDUCTION_CREATED` or `INDUCTION_UPDATED` events are added to a Prisoner's Timeline, whenever an Induction is created or updated via "our" API.
This now completes the functionality for creating and updating Inductions via our API (subject to more testing!). It also means that once we switch the CIAG UI to use our API, we can then remove all the SQS messaging code and config (including from cloud-platform-environments).

RR-448 - Induction Timeline events

---

helm_deploy/hmpps-education-and-work-plan-api/Chart.yaml
helm_deploy/hmpps-education-and-work-plan-api/values.yaml

This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `8 => 0 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have been …

Migrating project to use groups in allowlist

---

domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/DomainKeyAware.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/InPrisonInterests.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/PersonalSkillsAndInterests.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/EntityKeyAware.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InPrisonInterestsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PersonalSkillsAndInterestsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InPrisonInterestsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionEntityListManager.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/KeyAwareEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PersonalSkillsAndInterestsEntityMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InPrisonInterestsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdateInPrisonInterestsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdatePersonalSkillsAndInterestsEntityMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InPrisonInterestsEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PersonalSkillsAndInterestsEntityAssert.kt

This PR introduces `InductionEntityListManager`, which provides a centralised place for updating lists within Induction entities.
To minimise the size of this PR, I'm just starting with `InPrisonInterestsEntity` and `PersonalSkillsAndInterestsEntity`. I'll apply this approach to the remaining entities in subsequent PRs.
I might consider extending this for lists of entities outside of the Induction domain (primarily for Steps), but that would require a common module, which is shared between the domain model and is beyond the scope of this PR.

RR-469 - Centralised approach for updating lists within Induction entities

---

domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/Induction.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdateFutureWorkInterestsDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdateInPrisonInterestsDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdatePersonalSkillsAndInterestsDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdatePreviousQualificationsDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdatePreviousTrainingDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdatePreviousWorkExperiencesDto.kt
domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdateWorkOnReleaseDto.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/FutureWorkInterestsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InPrisonInterestsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PersonalSkillsAndInterestsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousQualificationsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousTrainingEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousWorkExperiencesEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/WorkOnReleaseEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsAndTrainingResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsAndTrainingResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/EducationAndQualificationsRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousWorkRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PrisonWorkAndEducationRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/SkillsAndInterestsRequestBuilder.kt

This PR fixes an issue where the domain objects could not be updated if they were null originally. It also ensures that a reference is not mandatory in the incoming update request objects!
Some of the logic is quite complex, so I've added comments to try and explain it.

RR-493 - Fix mapping when initial object is null

---

domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/UpdateInductionDto.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/FutureWorkInterestsResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PreviousWorkExperiencesResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/FutureWorkInterestsResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PreviousWorkExperiencesResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousWorkRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousWorkResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/UpdateCiagInductionRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/WorkInterestsBuilder.kt

This PR fixes two issues that would have resulted in breaking changes when migrating from the CIAG API to our API:
- Adds "modified" fields to the `WorkInterestsResponse` to make it match the CIAG API's response.
- Makes an Induction's `reference` field optional in the update request.
Once this is merged, I will scrutinise the JSON between the two APIs and make sure they match :)

RR-493 - Missing "modified" fields and optional reference field

---

README.md
helm_deploy/hmpps-education-and-work-plan-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
src/integrationTest/resources/application-integration-test.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/ApplicationStartupListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/CiagInductionMigrationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/WebClientConfiguration.kt
src/main/resources/application.yml

**DO NOT MERGE**
This PR provides a `WebClient` with a suitable authorizaton header that we will use to invoke the CIAG API for the purpose of CIAG Induction migration.
It also includes a `ApplicationStartedEvent` event listener (conditional on feature toggle) that in turn calls a basic service that we will build upon to actually perform the migration.
**DO NOT MERGE YET - we are too close to our private beta go-live to risk that release! We can merge this sometime next week**

RR-496 - Basic CIAG API webClient and application event listener

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/ApplicationStartupListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/CiagInductionMigrationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/AbilityToWorkFactor.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/AchievedQualification.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/CiagInductionResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/EducationAndQualificationResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/HighestEducationLevel.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/HopingToWork.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/InPrisonTrainingType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/InPrisonWorkType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/PersonalInterest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/PersonalSkill.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/PreviousWorkResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/PrisonWorkAndEducationResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/ReasonNotToWork.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/SkillsAndInterestsResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/TrainingType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/WorkExperience.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/WorkInterestDetail.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/WorkInterestsResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/resource/model/WorkType.kt

This PR adds model objects to deserialise the CIAG response, so that we can then map the data to temporary entities (to follow in a subsequent PR).

RR-503 - CIAG migration - deserialise CIAG response

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/CiagInductionTimelineEventTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundEventsServiceTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundEventBuilder.kt

Moved `CiagInductionEventBuilder` to "correct" package and renamed it `InboundEventBuilder` (because thats what it builds 😁 )

NO_JIRA - refactor CiagInductionEventBuilder to InboundEventBuilder in correct package

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/InductionController.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml

We know these paths are not ideal, but having the paths the same as the current CIAG API will make migrating the clients much much easier.
We will look to change the paths (and the request and response objects) when we re-design the API once we have migrated the UI clients

RR-508 - Change paths to match that of current implementation in CIAG API

---

build.gradle.kts
helm_deploy/values-dev.yaml
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/CiagInductionMigrationServiceTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/TestWebClientConfiguration.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/WiremockConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/CiagInductionMigrationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/CiagInductionPersistenceService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/CiagInductionPersistenceServiceTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/ciagmigration/WiremockService.kt

This PR implements the remaining functionality `CiagInductionMigrationService`, alongside a new service class: `CiagInductionPersistenceService`.
It also adds an integration test, which uses wiremock to simulate the retrieval of Inductions from the CIAG API.
As part of this PR, I've set the replica count to 1, as we may as well do this now. I'm planning on running this at least once before the UIs are ready to make sure everything is migrated across. I'll just need to delete the data inbetween.

RR-503 - Services for importing Inductions

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncInductionEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/GoalTelemetryEventType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/InductionTelemetryEventType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryEventTypeResolver.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryService.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncInductionEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryEventTypeResolverTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryServiceTest.kt

This PR adds AppInsights events for creating and updating CIAG Inductions.
We are only interested in these "high-level" events for the foreseeable future and are not sending specific details about the Inductions themselves.

RR-510 - App Insights events for Inductions

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PreviousWorkExperiencesResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/WorkInterestsBuilder.kt

This PR relaxes the validation and cardinality within the API so that we can accept create/update requests with completely null workExperience, along with empty collections elsewhere within the CIAG API.

RR-511 - Accept requests with null workExperience and empty collections

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/FutureWorkInterestsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InPrisonInterestsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PersonalSkillsAndInterestsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousQualificationsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousTrainingEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/WorkOnReleaseEntityMapper.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/WorkInterestsBuilder.kt

Technically the API was accepting an empty/null collection of qualifications when creating an induction, but this was then being mapped to a null collection in the domain object afterwards.
I had tests for sending null/empty lists of qualifications in update requests, but not create ones (though I had a test for sending no qualifications data, including no `educationLevel`).

RR-511 - Allow empty collections in create requests

---

domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalEventService.kt
domain/goal/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalService.kt
domain/goal/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalServiceTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncGoalEventService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncGoalEventServiceTest.kt

This PR fixes a problem where when saving multiple `GOAL_CREATED` events in the same request , they need to be saved with the same correlation ID
Previously they were being saved with a new correlation ID for each `Goal`. This has been changed so that irrespective of how many `Goal`s were created as part of the originating request, they all use the same correlation ID.

RR-512 - Save multiple GOAL_CREATED events with the same correlation ID

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/FutureWorkInterestsResourceMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/FutureWorkInterestsResourceMapperTest.kt

This PR changes the way we map work interests. Previously it was assumed that the UI should and would always send the array of `particularJobInterests`, since it always does when creating an Induction (even when no role is provided). However this is not the case when performing an update. For some reason, the UI does not ask for a role at all.

RR-511 - Mapping of workInterests

---

helm_deploy/values-dev.yaml

I suggest we run this after doing one more dry run of the data migration ASAP. Then we can run the migration on all 3 envs in one evening, once we've got the go ahead.

RR-516 Disable migration in dev

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapter.kt
src/main/resources/db/migration/V2023.12.05.0001__fix_actioned_by_on_timeline_events.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapterTest.kt

This PR fixes a problem with GOAL_UPDATED timeline events where the actionedBy fields were not being correctly set to the user that performed the goal update.
The problem was because the the goal was not saved & flushed within the Goal JPA Adapter , which meant the Goal that was returned from the method was the updated goal in respect of the fields mapped from the DTO, but crucially did not have the JPA managed fields updated on it.
---
I'm in 2 minds about whether to write a flyway migration to correct any current timeline event records that have the wrong actioned_by fields. Currently, using this query on `prod`, there are no affected records, which is good:
```
select te.* from timeline_event te 
inner join goal g on g.reference::text = te.source_reference
where te.event_type = …
```

RR-476 - Correctly set actionedBy fields when saving GOAL_UPDATED timeline event

---

src/main/resources/db/migration/V2023.12.05.0001__fix_actioned_by_on_timeline_events.sql

This is OK for this PR to update a flyway migration, as the migration in question failed previously, so it has never successfully run anywhere

RR-476 - Update flyway migration to correct any existing timeline event records

---

helm_deploy/hmpps-education-and-work-plan-api/templates/export-database-to-analytical-platform-cronjob.yaml

Temporarily disable the "export data to analytics platform" cronjob (with `suspend: true`) because it is likely that we will need to promote `main` to `preprod` and `prod` soon, but the analytical platform setup work is not yet complete in `preprod` and `prod` which means we can't allow the cronjob to run in those environments yet.

RR-446 - Temporarily disable cronjob

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PersonalSkillsAndInterestsResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/PersonalSkillsAndInterestsResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/EducationAndQualificationsRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/SkillsAndInterestsRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/SkillsAndInterestsResponseBuilder.kt

This PR introduces the swagger spec for a new endpoint to create Inductions. To keep it consistent with our other endpoints, this new endpoint will be available under `/inductions` (plural).
As part of this change, I've also deprecated the endpoints we migrated from the CIAG API and have tagged them as "Legacy":

RR-519 Swagger spec - new create Induction endpoint

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsAndTrainingResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/UpdateCiagInductionRequestMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsAndTrainingResourceMapperTest.kt

This PR ensures that an Induction can be updated if any of the "child" objects (e.g. `educationAndTraining`) is not provided in an update request.
I have also taken this opportunity to rationalise `UpdateInductionTest` and combine multiple scenarios into fewer tests where possible.

RR-521 Ensure null child objects are ignored when updating an Induction

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InductionEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/CiagInductionResponseMapper.kt

We've discovered an issue where the timestamp and author fields are wrong when an `INDUCTION_UPDATED` timeline event occurs. This was due to the way the main Induction's `updatedAt`/`updatedBy`/`updatedByDisplayName` fields were not being correctly updated in most circumstances when the "Update Induction" endpoint is called. This PR ensures that these fields are now updated whenever the update endpoint is called.

RR-548 - Ensure timestamp and author fields are updated

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CiagInductionController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagInPrisonInterestsResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagInductionResponseMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagSkillsAndInterestsResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagWorkExperiencesResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagWorkInterestsResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagWorkOnReleaseResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CreateCiagInductionRequestMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/QualificationsAndTrainingResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/UpdateCiagInductionRequestMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagInPrisonInterestsResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagInductionResponseMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagSkillsAndInterestsResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagWorkExperiencesResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagWorkInterestsResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CiagWorkOnReleaseResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/CreateCiagInductionRequestMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/ciag/QualificationsAndTrainingResourceMapperTest.kt

This PR is purely a precursor before adding a new `InductionController` and the necessary mappers for our new `/inductions` endpoints. It doesn't change any existing behaviour - it just renames/moves existing classes.

RR-522 - Precursor before adding new Induction endpoints

---

domain/timeline/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/Timeline.kt
domain/timeline/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/service/PrisonTimelineService.kt
domain/timeline/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/service/TimelineService.kt
domain/timeline/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/service/TimelineServiceTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonapi/PrisonApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonapi/PrisonApiException.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonapi/PrisonMovementEvent.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonapi/PrisonMovementEvents.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonapi/PrisonMovementType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/DomainConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaTimelinePersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/PrisonerApiTimelineService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaTimelinePersistenceAdapterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/PrisonerApiTimelineServiceTest.kt

This PR models the prisoner movement data we receive from the `prison-api` into a simplified set of data classes. The mapping between these and the `prison-api` classes, plus the subsequent inclusion into the prisoner `Timeline` domain will be done in subsequent PRs (I've added TODOs where relevant).
This PR also reverts the temporary code I added to the `JpaTimelinePersistenceAdapter` to test the connection to the `prison-api`.

RR-579 - Prisoner movement model and skeleton service class

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonapi/PrisonApiMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/mapper/PrisonMovementEventsMapper.kt
src/main/resources/static/openapi/PrisonApi.json
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonapi/PrisonerInPrisonSummaryBuilder.kt

This PR reverts the swagger spec back to the unmodified version that is currently provided by the [prison-api](https://prison-api-dev.prison.service.justice.gov.uk/v3/api-docs).
This results in the `date-time` format being removed from each of the relevant prison movement dates, since the provided format from the prison-api lacks the timezone indicator (meaning it can't be deserialized to an `OffsetDateTime`).

RR-566 Revert back to original prison-api spec

---

domain/timeline/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/Timeline.kt
domain/timeline/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/service/TimelineService.kt
domain/timeline/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/service/TimelineServiceTest.kt
helm_deploy/hmpps-education-and-work-plan-api/values.yaml
helm_deploy/values-dev.yaml
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetTimelineTest.kt
src/integrationTest/resources/application-integration-test.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/DomainConfiguration.kt
src/main/resources/application.yml
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/WiremockService.kt

This PR changes the logic for when a 404 (NOT FOUND) is returned from the GET timeline endpoint. Previously it returned a 404 if no PLP related events existed (i.e. if no Goals or Inductions have been created), which meant that no prison related information would be displayed on the Timeline view. Instead, we want the prisoner's prison history to be displayed, which is useful information for a CIAG, before they embark on an Induction.
This PR also removes the `callPrisonApiEnabled` feature toggle, since calling the prison API has been tested in dev and is ready to be rolled out to the other envs (client credentials have been setup in each env).

RR-592 - Remove feature toggle and change 404 response logic

---

helm_deploy/hmpps-education-and-work-plan-api/values.yaml

PR to add temporary envs vars, which we will then remove in a subsequent PR and hope that helm removes them from the environment.

RR-641 Add temporary env vars

---

helm_deploy/hmpps-education-and-work-plan-api/values.yaml

There's a bit of history to this PR, but in a nutshell we have 2 secret variables hanging around which we need to remove. Otherwise, we can't remove the subsequent SQS secrets from CPE and fully decommission the remnants of the CIAG API.
This PR adds temporary secret variables, which we will then remove in a subsequent PR and hope that helm removes them from the environment.

RR-641 Temporary add legacy (incorrect) secrets

---

helm_deploy/hmpps-education-and-work-plan-api/values.yaml

Clutching at straws here, but I was a bit reluctant about removing this property in my previous PR (even though I added it for the domain-events SQS functionality a few months ago).

RR-641 - Restore serviceAccountName (test)

---

build.gradle.kts
domain/goal/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/GoalTest.kt
domain/induction/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionServiceTest.kt
domain/timeline/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/TimelineTest.kt
domain/timeline/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/service/TimelineServiceTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ciag/CreateCiagInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ciag/GetCiagInductionSummariesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonapi/PrisonApiMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdateFutureWorkInterestsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdatePreviousQualificationsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TelemetryServiceTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonapi/PrisonerInPrisonSummaryBuilder.kt

This PR bumps the dependency versions of the gradle build to the latest versions to fix the latest OWASP vulnerabilities that are being logged in the nightly scan.
It's actually quite a big PR - bigger than what I anticipated, but I think thats a reflection of the fact we've not done this for a while (and perhaps should do more often)
Anyway, as well as the version bumps in the gradle build, theres a lot of "code changes" caused by linting errors (you're gonna love this @mattwills-moj-digital ! )
It seems one of the more recent changes in HMPPS Spring Boot gradle plugin has changed the linting rules! 😢 (either by bumping the version of the linter, or making a conscious decision to change them. Either way, I've had to make quite a few changes to the code to fix them!
The main (annoying) …

Dependency bumps to fix OWASP vulnerabilities

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ActionPlanController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CiagInductionController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GlobalExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/InductionController.kt

This PR handles DB exceptions in the GlobalExceptionHandler to prevent them being leaked in the error response
There's also some minor work around where the transaction boundary is because otherwise the induction would have been created even though it was the timeline record that failed to write (it feels correct that if the timeline failed to update, then the main request should also fail)
Without this fix, this is the error response that leaks details:
```
{
"status": 500,
"errorCode": null,
"userMessage": "Unexpected error: could not execute statement [ERROR: value too long for type character varying(3)] [insert into timeline_event (timeline_id,actioned_by,actioned_by_display_name,contextual_info,correlation_id,created_at,event_type,prison_id,reference,source_reference,timestamp,id) …
```

RR-741 - Handle DB exceptions to prevent them being leaked in the error response

---

build.gradle.kts
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetTimelineTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/HmppsEducationAndWorkPlanApi.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/ThreadPoolConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncActionPlanEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncGoalEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncInductionEventService.kt

This PR makes our async services properly async by using Spring's `ThreadPoolTaskExecutor` and the `Async` annotation.
([based on this medium post](https://medium.com/@ahmedmohamedmar3y2017/springboot-asynchronous-methods-58524b444fb4))
The original code was always meant to be async, but was flawed. It attempted to use kotlin coroutines, but the use of the `runBlocking` annotation meant that it wasn't async at all and actually was blocking the main request thread.
(There is an [alternative PR](https://github.com/ministryofjustice/hmpps-education-and-work-plan-api/pull/278) that implements these async services using kotlin coroutines)

RR-799 - Async services using Spring's ThreadPoolTaskExecutor

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetConversationTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateConversationTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/conversation/ConversationEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ConversationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/conversation/ConversationsResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/conversation/ConversationResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/conversation/ConversationResponse.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/conversation/ConversationResponseAssert.kt

Adds the implementation for the get conversation endpoint.
This PR also removes the `/{prisonNumber}` path param from the get and update conversation endpoints since it wasn't necessary.

RR-797: Get conversation endpoint implementation

---

.trivyignore
build.gradle.kts
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationServiceTest.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionServiceTest.kt
domain/personallearningplan/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/GoalTest.kt
domain/personallearningplan/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/ActionPlanServiceTest.kt
domain/personallearningplan/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalServiceTest.kt
domain/timeline/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/timeline/service/TimelineServiceTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonapi/PrisonApiClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapterTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/JwtAccessTokenBuilder.kt

This PR fixes a load of build warnings about the use of a deprecated version of the assertJ method `catchThrowableOfType`
This has come about since the recent update to HMPPS `spring-boot-gradle-plugin:6.0.0` which presumably brings with it a later version of Spring which in turn brings a later version of assertJ as a transitive dependency 🤷‍♂️ 
Anyway, this PR changes the previous use of `catchThrowableOfType` to a different method overload (same method, it's just the args are in a different order)
It also commits the change to `.trivyignore` which again is the result of updating to HMPPS `spring-boot-gradle-plugin:6.0.0` 
And also some changes to the use of some JWTS code, again based on updating `spring-boot-gradle-plugin` which brings in a newer version of JWTS which deprecates some …

NO_JIRA - fixed deprecated assertion method calls following update to hmpps spring-boot-gradle:6

---

helm_deploy/values-dev.yaml

PR to add the `prisons` group to the `dev` allowlist (dev only)
This is so that a HMPPS analytics team can access the swagger spec for some analysis they are doing. They do not use developer spec laptops, and instead use HMPPS "prison" spec devices. The user is question is coming in on IP `moj-official-ark-c-expo-e: "51.149.249.0/29"` which is part of the `prisons` predefined IP range group.

NO_JIRA - Add `prisons` group to `dev` allowlist

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateInductionTest.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml

This PR implements format validation for the `prisonId` field in our API request bodies.
This problem actually came up as part of our appSec security scan where they identified that submitting a request with a malformed prisonId cause and exposed a SQL exception (that they quite rightly said could be used to garner information and prepare an attack)
Whilst we acknowledged that lack of validation was the root cause it also identified the fact that our code that wrote to the timeline database (which is the db write that failed) was not async fire and forget.
At the time we chose to use this problem to fix our async code so that it was fire and forget and that any errors were not thrown back and returned in the main request thread. Hence the test that this PR now removes/changes.
We wrote …

RR-800 - Added request validation for `prisonId` fields

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/ResourceServerConfiguration.kt

APSEC reported that a JSESSIONID cookie is being set in some scenarios.  We make no use of the session and therefore session hijack is not an issue, however it could conceivably be a denial of service attack vector.
If unauthenticated, Spring security was rejecting the request and creating the session so that it could store the original URL and redirect back to it if this was part of an authentication flow. That is something not supported in our auth model and can be disabled.

RR-759: Prevent session creation on auth failure

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/exception/ReturnAnErrorException.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GlobalExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalControllerTest.kt

Change to throw exception for unhappy paths and return the type directly. This will fix the swagger docs without the need for adding response type annotations.

RR-826: Keep type on controller for swagger gen

---

domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/GetGoalsDto.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalService.kt
domain/personallearningplan/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalServiceTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetGoalsTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalControllerTest.kt

This PR introduces support for the getGoals API endpoint to specify zero, one or more statuses on the `status` query string parameter.

RR-880 - getGoals now supports multiple statuses as a query string parameter filter

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

This PR changes the start time of the `generic-data-analytics-extractor` job in `dev` and `preprod` to 07:00 Monday-Friday which is a time when the database is up!
Previously the job ran at 01:00 7 days a week. However in `dev` and `preprod` we terminate resources (like the database!) out of working hours to save a few pennies, so the job could never attach to the database! Doh! 🤣 
This does not change the time in `prod`, which is still set to run at 01:00 every day.
See discussion here: https://mojdt.slack.com/archives/C05BDTUL64E/p1721288755297809

NO-JIRA - Change the start time of the generic-data-analytics-extractor job to a time when the database is up!

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetTimelineTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/FutureWorkInterestsResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/InPrisonInterestsResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/InductionResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PersonalSkillsAndInterestsResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousQualificationsResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousTrainingResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/WorkOnReleaseResponseAssert.kt

PR to tidy a few test compile time warnings, specifically those to do with kotlin non-null safe operations:
```
w: file:///Users/nathan.russell/projects/hmpps/hmpps-education-and-work-plan-api/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetInductionTest.kt:106:18 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.InductionResponse?'.
w: file:///Users/nathan.russell/projects/hmpps/hmpps-education-and-work-plan-api/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetInductionTest.kt:107:18 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type …
```

Tidy test warnings re: InductionResponse

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/actionplan/GoalEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousQualificationsEntityMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapterTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousQualificationsResponseAssert.kt

This PR fixes a bug when updating an induction that previous had no qualifications, but the update now contains qualifications.
Specifically the scenario is:
* An `Induction` exists, and when that induction was first created no `previousQualifications` (Highest Level of Education, or Qualifications) were added
(Highest Level of Education and Qualifications used to be entirely optional at the UI, so there will be existing `Induction` records in the database where the corresponding `PreviousQualificationsEntity` is null
* The `Induction` is subsequently updated in the UI by adding previous qualifications (either Highest Level of Education, or Qualifications)
This always used to work, but now that `PreviousQualificationsEntity` contains the `prisonNumber` field, we now have a bug in the …

RR-900 - Fix bug when updating induction with new qualifications

---

.circleci/config.yml
build.gradle.kts
helm_deploy/hmpps-education-and-work-plan-api/values.yaml
helm_deploy/values-dev.yaml
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/testcontainers/LocalStackContainer.kt
src/integrationTest/resources/application-integration-test.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/RawJsonDeserializer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/AdditionalInformation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/EventType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundEvent.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundEventsListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundEventsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedIntoPrisonEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReleasedFromPrisonEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/SqsMessage.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundEventsServiceTest.kt

This PR adds the basic setup and config to consume and process HMPPS Domain Events, specifically  `prison-offender-events.prisoner.received` and `prison-offender-events.prisoner.released`
The actual logic for how we consume each of these events will be in subsequent PRs - this is just the basic infrastructure
The listener bean is disabled in `preprod` and `prod`, but is enabled in `dev`
There are unit tests in this PR. Whilst there are no integration tests yet, the integration test setup including circleci setup has been done.

RR-920 - Basic setup to listen to HMPPS Domain Events

---

helm_deploy/hmpps-education-and-work-plan-api/values.yaml
helm_deploy/values-dev.yaml

This PR enables listening to SQS messages in `preprod` and `prod` by setting the env var `HMPPS_SQS_ENABLED` to `true` in all helm deployed environments.

RR-920 - Enable SQS listener in preprod and prod

---

src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/education/AchievedQualificationResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/education/AchievedQualificationResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/education/EducationResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/education/EducationResponseBuilder.kt

This PR is part of a larger piece of work (RR-901, specifically implementing the GET endpoint for returning a prisoner's education/qualifications outside of an induction). I've done the work, but it represents a large PR (40 files), so felt it would be easier for review purposes to break it up and do PRs for each logic section. 
This PR is the first in that process.
---
This PR updates the GET education endpoint definition in the swagger spec, and adds the text fixture classes we will use.
A previous PR had defined the GET endpoint, but on subsequent analysis we determined would could not fulfil all of the data items in the response. Specifically the "display name" of the user who created/updated the education record, and the prisonId where it was created/updated. We are not able to …

RR-901 - Update swagger spec and introduce test fixtures

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/AdditionalInformation.kt

This PR adds some missing enum values and fixes field cardinality in respect of the HMPPS Domain Events that we listen to.
At the moment we are seeing a couple of problems in `prod` where the messages cannot be deserialized into our types. Most of these seem to be from the missing enum value `BEING_TRANSFERRED`, and some are based on the fact that we have the `details` field as non-nullable where in reality it can be null.
eg:
The offender events swagger spec (where I was pointed at by the HMPPS dev community initially) is misleading / wrong, so I will separately raise a PR on that to correct it.
Notice the missing enum value `BEING_TRANSFERRED`, the fact that `details` is incorrectly spelt as `detail` and none of the fields describe whether they are nullable or not.

RR-920 - Fix enums and message field cardinality

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousQualificationsResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousQualificationsResponseBuilder.kt

This PR changes the REST API `GET /inductions/{prisonNumber}` response so that it returns qualifications as collection of `AchievedQualificationResponse` rather that a collection of `AchievedQualification`
`AchievedQualificationResponse` as a type already exists and is the same as `AchievedQualification` except that it also contains the reference and audit fields (who/when created & updated). 
The reason we need this is part of supporting the changes we need to make for Qualifications and the change to the user journey. We need to show the audit fields (who/when created & updated) for each Qualification; and also we will need to be able to have better control over how we edit the prisoner's Qualifications, so having the reference for each Qualification will allow us to edit individual …

RR-901 - Return AchievedQualificationResponse as part of REST API InductionResponse

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsResourceMapper.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/CreatePreviousQualificationsRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/UpdatePreviousQualificationsRequestBuilder.kt

This PR makes a change to the REST API spec to allow the reference number to be optionally passed in when creating qualifications as part of the Induction. This allows for qualifications to already exist (created by an earlier process by the Education team), and for them to be included in the Induction where they will be treated as existing Qualifications rather than created as new (and therefore duplicate) Qualifications.
(This PR is the API and basic mapping only, not the full implementation yet)

RR-901 - Pass optional reference in when creating or updating quals

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/PreviousQualifications.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/dto/CreatePreviousQualificationsDto.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/dto/UpdateOrCreateQualificationDto.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/dto/UpdatePreviousQualificationsDto.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/PreviousQualificationsBuilder.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/dto/PreviousQualificationsDtoBuilder.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/dto/UpdateOrCreateQualificationDtoBuilder.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousQualificationsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/education/EducationResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsResourceMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdatePreviousQualificationsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/CreatePreviousQualificationsRequestBuilder.kt

This PR changes the API implementation re: creating and updating individual qualifications as part of the create or update Induction requests.
Previously when creating an Induction it was assumed there were no child elements of the induction already recorded in the system. (eg: pre-existing qualifications recorded before the Induction was created) This is still true because at time of writing it is not possible to create qualifications (or other resources) outside of the context of the parent Induction.
But we will soon be changing that, so that you will be able to create Qualifications before in the induction.
Therefore, to support that, the Create Induction implementation has been changed so that for any qualifications in the Create Induction request; if they have no reference number …

RR-901 - Implementation to update qualifications identified by their reference number

---

helm_deploy/values-dev.yaml
helm_deploy/values-prod.yaml

This PR changes the cron schedule of the SQS housekeeping job for dev and preprod
It was set to every 10 minutes (and still is in production), but in dev and preprod we shut down a lot of the AWS resources (such as the service itself, and all of its dependant resources like the database etc) from 9pm till 06:30am and all weekend.
Because the main service is shutdown overnight and over the weekend, it meant that we get loads of errors every 10 minutes when the housekeeping job kicks in!
The PR sets the cron schedule (in dev and preprod only) to take the scheduled downtime into consideration

Fix housekeeping cron schedule in dev and preprod to allow for scheduled downtime

---

src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml

This PR updates the swagger spec to add `maxLength` properties to all the Induction fields that should have a length constraint.
This PR goes hand in hand with the [corresponding UI PR](https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/pull/764) that adds UI validation to the UI forms.
Basically it's belt'n'braces / doing the right thing. 
With this change the swagger spec now clearly communicates the field length constraints:
and the generated model classes get the JSR annotation which will be validated by Spring, with the request being rejected with a 400 if the constraint is violated:

RR-938 - Added maxLength properties to Induction fields

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/dto/UpdatePreviousQualificationsDto.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/dto/PreviousQualificationsDtoBuilder.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/InductionResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsResourceMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/InductionResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsResourceMapperTest.kt

This PR adds the prisoner's `prisonNumber` to `UpdatePreviousQualificationsDto` and the associated changes to the mappers etc. This change (adding `prisonNumber`) is necessary to support updating a prisoner's qualifications outside of the context of updating the Induction (so it was a case of either do it here in a smaller PR, or include it in the PR that allows qualifications to be edited 🤷‍♂️  )

RR-901 - Refactor UpdatePreviousQualificationsDto to include the prisonNumber

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/PreviousQualifications.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/dto/UpdateOrCreateQualificationDto.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/PreviousQualificationsBuilder.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/dto/UpdateOrCreateQualificationDtoBuilder.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateEducationTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaEducationPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PreviousQualificationsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousQualificationsEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/education/EducationResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsResourceMapper.kt
src/main/resources/db/migration/common/V2024.11.09.0001__add_prison_id_fields_to_qualification.sql
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousQualificationsEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdatePreviousQualificationsEntityMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PreviousQualificationsEntityBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/education/AchievedQualificationResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/education/AchievedQualificationResponseBuilder.kt

This PR adds the `createdAtPrison` and `updatedAtPrison` audit fields to individual qualifications.
The Previous Qualifications object (that is effectively a container for all things "qualifications") contains the prisoner's Highest Level of Education and a collection of Qualifications. It has always contained the full set of "audit" fields (`createdAt`, `createdBy`, `createdByDisplayName`, `createdAtPrison`, `updatedAt`, `updatedBy`, `updatedByDisplayName`, `updatedAtPrison`)
Individual qualifications previously only had a subset of these audit fields because that suited the requirements at the time - 
(`createdAt`, `createdBy`, `updatedAt`, `updatedBy`)
This PR adds the `createdAtPrison` and `updatedAtPrison` audit fields to individual qualifications. The updates to the mappers ensures …

RR-935 - Add createdAtPrison and updatedAtPrison to individual qualifications

---

README.md
build.gradle.kts
helm_deploy/hmpps-education-and-work-plan-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
src/integrationTest/resources/application-integration-test.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonersearch/PagedPrisonerResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonersearch/PrisonerSearchApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonersearch/PrisonerSearchApiException.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/WebClientConfiguration.kt
src/main/resources/application.yml

This PR adds a client for calling `prisoner-search-api`
Currently nothing uses it - this PR just introduces the class, the basic wiring, and the config.
As part of this I've asked the HAAR team to create new client creds for us (in all 3 envs) with the appropriate role (ROLE_PRISONER_SEARCH)
Whilst I was talking to HAAR I also took the opportunity to ask them to create client creds for manage-users-api 👍 
Using the dev client creds they created, I have manually tested using them against the dev APIs, all works fine 👍 
Also updated the readme in a number of places.

RR-983 - Added prisoner-search-api client class and supporting code

---

docs/ciag-kpis/CIAG KPI1 - PEF Apr 25 to Oct 25.mermaid
docs/ciag-kpis/README.md

This PR documents the new proposed flow in for KPI1 as discussed with Matt Ryall and Stephen Mcallister.
The basic idea is that we do not try to use lots of backwards & forwards granular events to try to co-ordinate / orchestrate processes within 2 otherwise unconnected systems (PLP and Curious)
Instead PLP does it's thing and manages its own state/process. But every time that the Induction Schedule is updated for any reason, it publishes an SNS message (the detail of which is not defined in this PR/spec). 
HMPPS Integration API processes this event via a subscription and queue to the message and calls PLP's REST API to get the details of the Induction Schedule (again, the detail of which is not the scope of this PR)
HMPPS Integration API then publishes an SNS message which is received …

RR-918 - Updated sequence diagram for KPI 1

---

.circleci/config.yml
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/note/service/NotePersistenceAdapter.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/note/service/NoteService.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UnarchiveGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaNotePersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/repository/NoteRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ActionPlanController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/actionplan/GoalResponseAssert.kt

Follow on work from the previous work to add (Archive) Goal notes. This PR returns a list of notes when a  goal is presented to the UI, Currently these are GOAL and ARCHIVE notes but in the future this will include GOAL_COMPLETE notes. 
The existing mechanism for getting goal notes has been retained.
Additionally, Circle CI config has been updated to display test results in the event of a test failure.

adding notes to get action plan

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/manageusers/ManageUsersApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/note/NoteMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ActionPlanController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/GoalResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/conversation/ConversationsResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/note/NoteResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/ManageUserService.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/GoalResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/conversation/ConversationResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/note/NoteResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/validator/UpdateGoalRequestReferenceConstraintValidatorTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/actionplan/GoalResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/actionplan/GoalResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/note/NoteResponseBuilder.kt

This PR maps the createdByDisplayName and updatedByDisplayName fields in Note in the REST API responses to be mapped from the user service (ie. look them up from the API call)
We need to make this change on all REST API responses where the resource contains createdByDisplayName and updatedByDisplayName fields - this PR just does Notes
In order to do this change I have:
* Renamed Notes to NotesResponse (consistent with our other response model types)
* added the createdByDisplayName and updatedByDisplayName fields to NoteResponse
* added the other audit related fields to NoteResponse (not strictly necessary for this PR, but I was there anyway and it made sense to do them)
* created and used a new mapper to map NoteDto domain instances into NoteResource instances, including looking up the …

RR-998 - Added displayName fields to NotesResource and related mappers

---

domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalNotesService.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalService.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/GoalNoteService.kt

When the the goal note is set to be a blank string or null and there is an existing goal note - then delete it.

Delete goal note when update note is blank

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/GoalResourceMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/GoalResourceMapperTest.kt

This PR maps the `displayName` fields for goal resources by looking up the user from the user service.
The mapper concerned is `GoalResourceMapper` and in making this change I have taken the opportunity to re-implement the mapper as a regular class, rather than a MapStruct mapper interface

RR-997 - Mapped displayName fields in GoalResourceMapper via user lookup

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/timeline/TimelineEventResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/PrisonerApiTimelineService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/mapper/PrisonMovementEventsMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/timeline/TimelineEventResourceMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/mapper/PrisonMovementEventsMapperTest.kt

This PR fixes a bug with the user details (display name) lookup for the timeline.
The timeline is a list of events that have happened. Some of those events are instigated by a DPS user (eg: PLP events such as updating a goal etc), but other events are "system" events and dont have an associated user (eg: prisoner movement events)
On the timeline UI prison movement events are rendered without the name of who performed the action, and PLP events show the user who performed the action:
and
The change made in my last PR was this:
```
actionedByDisplayName = userService.getUserDetails(actionedBy).let {
if (it.active) it.name else null
},
```
This did the user lookup (even for the system user) and if the returned UserDetails was `active` then it returned the name, else it returned null.
This …

RR-1004 - Dont lookup userDetails for "system" user

---

docs/ciag-kpis/CIAG KPI1 - PEF Apr 25 to Oct 25.mermaid
docs/ciag-kpis/CIAG KPI1 - PES post Oct 25.mermaid

PR to update the sequence diagrams for KPI1
Significant changes:
* PEF (Apr - Oct)
* Deadline date is today + 20 days (confirmed with Aliki)
* Changed Integration API so that it does not lookup & store, but instead is a pass-thru proxy
* Renamed the "NOMIS" participant to "DomainEvents" as that better reflects the participant / responsibility
* PES (post Oct)
* Essentially the same as PEF but with:
* Initial Induction Schedule created without a deadline date
* Curious to call Integration API's PUT endpoint to notify relevant S&A's complete
* Induction Schedule deadline date set to today + 10 days (confirmed with Aliki) on notification of S&As being complete

RR-918 - Update KPI1 sequence diagrams

---

docs/ciag-kpis/CIAG KPI1 - PEF Apr 25 to Oct 25.mermaid
docs/ciag-kpis/CIAG KPI1 - PES post Oct 25.mermaid

This PR removes the unused `HMPPS Integration DB` participant from the KPI1 sequence diagrams
(I forgot to remove them in my last PR)

RR-918 - Remove unused `HMPPS Integration DB` participant from sequence diagrams

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/note/dto/UpdateNoteDto.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalNotesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/note/NoteEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/GoalNoteService.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/note/NoteEntityBuilder.kt

This PR makes a minor refactoring to the `NoteEntity` class to make it a data class, and to it's `content` field to make it non-nullable (and the same change in the DTO, mappers etc)
I've needed to make this change because it was biting me a little in respect of the "Submit Review" API endpoint I am implementing because it needs to persist a NoteEntity as part of submitting the Review
(To be fair, it wasn't strictly necessary, I could have coded around it, but it's neater this way)

RR-1088 - Refactor NoteEntity as a data class, make content field non-nullable

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/Exceptions.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/ReviewSchedule.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/dto/CreateReviewScheduleDto.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/dto/UpdateReviewScheduleDto.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewSchedulePersistenceAdapter.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/ReviewScheduleBuilder.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/dto/CreateReviewScheduleDtoBuilder.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/dto/UpdateReviewScheduleDtoBuilder.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaReviewSchedulePersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/review/ReviewScheduleEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/review/ReviewScheduleEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/repository/ReviewScheduleRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/review/ScheduledActionPlanReviewResponseMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaReviewSchedulePersistenceAdapterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/review/ReviewScheduleEntityMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/review/ReviewScheduleEntityBuilder.kt

This PR creates the persistence adapter methods and supporting code to allow a `ReviewScheduleEntity` to be created, and to to be updated
Once we have this in place the Review service methods which will persist a Review and update the Review Schedule should be straightforward 🤞

RR-1088 - Persistence classes to create and update a ReviewScheduleEntity

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/SentenceType.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/dto/CreateCompletedReviewDto.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewPersistenceAdapter.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewService.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewServiceCalculateReviewWindowTest.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewServiceDetermineReviewScheduleCalculationRuleTest.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewServiceTest.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/dto/CreateCompletedReviewDtoBuilder.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaReviewPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/note/NoteMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/review/ReviewEntityMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaReviewPersistenceAdapterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/review/ReviewEntityMapperTest.kt

Once this PR is approved and merged I should be able to create a service method to create a completed review, whose implementation will use all the stuff that these recent PRs have been adding (ie. it will need to check a ReviewSchedule exists, create the new Completed Review, call the methods to work out the calculation rule and next schedule, and then update the ReviewSchedule with the next schedule etc.
And once we've got the service method in place then it will be an easy job to create the controller method which will call it 👍

RR-1088 - Persistence adapter etc for persisting a new Completed Review

---

helm_deploy/values-dev.yaml

Disable the ingress allowlist for the API **on `dev` only**
This is to allow the Integration API to consume the API's swagger spec
As per the following conversation with Matt Ryall this is not ideal but we dont have other options in the short term:

allow all on dev

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/messaging/InboundEventsListenerTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/ManageUserService.kt

instead of system not found since system doesn't have a user account.

return system as the display name

---

docs/ciag-kpis/CIAG KPI1 - PES post Oct 25.mermaid
docs/ciag-kpis/CIAG KPI2.mermaid
docs/ciag-kpis/README.md

This PR adds the sequence diagram for CIAG KPI2; and updates the message type names in the KPI1 diagrams.
Proposed KPI2 Sequence Diagram can be viewed [here](https://github.com/ministryofjustice/hmpps-education-and-work-plan-api/blob/feature/RR-1166-kpi2-sequence-diagram/docs/ciag-kpis/CIAG%20KPI2.mermaid)

RR-1166 - KPI2 sequence diagram; updated message types in KPI1 diagrams

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/PrisonerSearchApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/PrisonerSearchApiServiceTest.kt

This PR changes the `getAllPrisonersInPrison` method to get all prisoners via paged calls on the prisoner-search API
There is probably a smarter way of doing this using Flux or similar, but that would mean making the whole stack non-blocking (WebFlux) and life is too short! 🤣

RR-1162 - Get all prisoners in prison via paged API call

---

domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/ActionPlan.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/ActionPlanSummary.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/CreateActionPlanDto.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/ActionPlanService.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalService.kt
domain/personallearningplan/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalServiceTest.kt
domain/personallearningplan/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/ActionPlanBuilder.kt
domain/personallearningplan/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/ActionPlanSummaryBuilder.kt
domain/personallearningplan/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/CreateActionPlanDtoBuilder.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanSummariesTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetTimelineTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/actionplan/ActionPlanEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/actionplan/ActionPlanSummaryProjection.kt
src/main/resources/db/migration/common/V2024.12.06.0001__drop_review_date_column_from_action_plan.sql
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/actionplan/ActionPlanEntityTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/actionplan/ActionPlanEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/ActionPlanResourceMapperTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/actionplan/ActionPlanEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/actionplan/ActionPlanEntityBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/actionplan/ActionPlanSummaryProjectionBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/actionplan/ActionPlanResponseAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/actionplan/ActionPlanResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/actionplan/ActionPlanSummaryResponseBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/actionplan/CreateActionPlanRequestBuilder.kt

This PR removes the `review_date` field from the `action_plan` table, and all the way up the stack (DB entity, domain, and on to the REST API; and all associated mappers, test data builders, assertion classes etc)
It's a lot of change to remove one field! 🤣 
Very early in the PLP development, the business spoke about the concept of "action plans being reviewed" (where an action plan is a prisoner's Induction and Goals). They've always had the idea that Action Plans would be reviewed; but their initial thought process and designs were unrelated to the work we are now doing with Reviews, Curious/MN, and KPI2.
At the time they didn't have final or tested screen designs, and hadn't thought through the process about how a review date might get set, and how a review would take place. All they …

RR-227 - Remove reviewDate from Action Plan

---

domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/ActionPlan.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/Exceptions.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/ActionPlanService.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalService.kt
domain/personallearningplan/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/ActionPlanServiceTest.kt
domain/personallearningplan/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalServiceTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ArchiveGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CompleteGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalsTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetGoalsTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UnarchiveGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/DomainConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/SubjectAccessRequestService.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/SubjectAccessRequestServiceTest.kt

This PR completes RR-227 by addressing the TODO now that the UI has been changed to call the `createActionPlan` API endpoint.
Basically there were 3 TODO's to address:
1. Enable the code to throw an exception when a Action Plan is created with no goals
2. Throw an exception (which results in a 404) when attempting to get an Action Plan that does not exist (previously it returned a "dummy" Action Plan with no goals
3. Throw an exception (which results in a 404) when attempted to create goals but for an Action Plan that does not exist (previously it created an Action Plan)
Pretty much all of the other changes in this PR are changes to the tests to reflect the new behaviour.

RR-227 - Address TODOs

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateActionPlanReviewStatusHistoryTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateActionPlanReviewStatusTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaReviewSchedulePersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/review/ReviewScheduleHistoryEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/repository/ReviewScheduleHistoryRepository.kt
src/main/resources/db/migration/common/V2024.12.10.0001__add_review_schedule_history_table.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaReviewSchedulePersistenceAdapterTest.kt

Pretty straightforward method of storing history for review schedule entities. 
Whenever we call save just call the saveReviewScheduleHistory method after and the history will be recorded, subsequent saves will increment the version number on the history entity. 
I did attempt to do this with a Jpa listener but burned too much time on it and I think may have been [impossible](https://stackoverflow.com/questions/71348249/spring-jpa-calling-repository-method-inside-entitys-life-cycle-method)

store history for review schedule changes

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateActionPlanReviewStatusHistoryTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateActionPlanReviewStatusTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ReviewController.kt
src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/review/UpdateReviewScheduleStatusRequestBuilder.kt

Renamed `CreateReviewScheduleStatusRequest` to `UpdateReviewScheduleStatusRequest` to better align it to it's use case / controller method
IE. its the request body to Update the Review Schedule Status, not to create it

RR-1049 - Renamed CreateReviewScheduleStatusRequest to UpdateReviewScheduleStatusRequest

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetGoalsTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt

PR to fix a bug where the response data from the `getGoals` API response does not currently map in the associated notes for each goal.

RR-1170 - Map notes into GoalResponses

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleService.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleServiceTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedEventTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReleasedEventTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReleasedFromPrisonEventService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReleasedFromPrisonEventServiceTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/AdditionalInformationBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/SqdMessageBuilder.kt

This PR adds the listener for the prisoner released event, and implements the code to update their Review Schedule as necessary:
* If the prisoner does not have a Review Schedule, do nothing
* If the prisoner has a Review Schedule, but it is already `COMPLETE` (ie. they have already had their last review before release), do nothing
* All other cases, update the Review Schedule to have status `EXEMPT_PRISONER_RELEASE`

RR-1020 - Added listener for prisoner.released event

---

domain/timeline/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/timeline/TimelineEvent.kt
domain/timeline/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/timeline/TimeLineBuilder.kt
domain/timeline/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/timeline/TimelineEventAssert.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/timeline/TimelineEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/timeline/TimelineEventEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/timeline/TimelineEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/timeline/TimelineEventEntityMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/timeline/TimelineEventResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncConversationEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncInductionEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TimelineEventFactory.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/mapper/PrisonMovementEventsMapper.kt
src/main/resources/db/migration/common/V2024.12.29.0001__drop_display_name_field_from_timeline_event_table.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/timeline/TimelineEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/timeline/TimelineEventEntityMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncConversationEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncInductionEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncReviewEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TimelineEventFactoryTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/timeline/TimelineEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/timeline/TimelineEntityBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/timeline/TimelineEventEntityAssert.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/timeline/TimelineEventEntityBuilder.kt

This PR is the first of a few very similar ones that we'll need to do over the next couple of weeks , and is related to the RBAC work.
RBAC is going to become important again soon because we need to have different roles etc for users who can do reviews etc; and in order to do the RBAC work (more specifically, to create granular roles) we need the UI to not use the user token, and instead use the system token. 
We've done this work for the read operations that the UI makes 👍 , but not the write operations yet. In preparation for doing the changes to the write operations (to use the system token) we need to remove the code in the API that writes the "display name" fields to the database entities via the custom annotation that uses the username claim from the token. (ie. before we can get …

RR-1203 - Remove displayName field from Timeline Entity

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleService.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReleasedDueToDeathEventTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/AdditionalInformation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReleasedFromPrisonEventService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReleasedFromPrisonEventServiceTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/AdditionalInformationBuilder.kt

This PR continues the work re: automatically exempting a prisoners Review due to the `prisoner.released` event.
A previous PR added the basic code to listen to the `prisoner.released` event and exempt the prisoner's Review Schedule; though that PR did not consider _why_ the prisoner had been released (`nomisReasonCode`)
This PR changes that so that if the prisoner is released the Review Schedule is exempted with status `EXEMPT_PRISONER_RELEASE`
But if they are released due to death (`nomisReasonCode == DEC`), then the Review Schedule is exempted with status `EXEMPT_PRISONER_DEATH`

RR-1020 - Exempt prisoners Review on prisoner.released event (due to death)

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleDateCalculationService.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleService.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleDateCalculationServiceTest.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleCalculationServiceTest.kt

Initial `InductionScheduleDateCalculationService` and basic refactoring
This follows a similar pattern to what we did earlier with the `ReviewScheduleDateCalculationService`, I have introduced the class `InductionScheduleDateCalculationService` with the view that all Induction Schedule date calc logic lives in one place.
At the moment I've only moved some of the logic from other classes into it - we can move some more in subsequent PRs

RR-1198 - Initial InductionScheduleDateCalculationService

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleService.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewService.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleServiceTest.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewServiceTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ReviewController.kt

This PR is part of some tidying/refactoring of InductionSchedules and how they are calculated, but also ReviewSchedules where it makes sense (as they are so closely related)
This PR moves the function `getReviewSchedulesForPrisoner` from `ReviewService` to `ReviewScheduleService` which is a more logical place for it.
There are a couple of other "review schedule" related functions that are currently in `ReviewService` that I will look at moving to `ReviewScheduleService` shortly ... 🤔

RR-1198 - Move getReviewSchedulesForPrisoner to ReviewScheduleService

---

domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/InductionBuilder.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/note/dto/CreateNoteDtoBuilder.kt
domain/timeline/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/timeline/TimelineEventAssert.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TimelineEventFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TimelineEventFactoryTest.kt

Fix for the contextualInfo field of the ACTION_PLAN_CREATED timeline event
We only want to write it if the induction was created using the new UI journey

RR-1213 - Fix contextualInfo for ACTION_PLAN_CREATED timeline event

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonersearch/PagedPrisonerResponse.kt

Found while testing the ETL - it is possible for the legal status to be returned as null from prisoner search api. 
Whether this could happen in live or not I don't know but propose this change to at least prevent the ETL from failing.

handle when legal status is null

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleDateCalculationService.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/ReviewSchedule.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleDateCalculationService.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleService.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewService.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleServiceCreateInitialReviewScheduleTest.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleServiceTest.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewServiceCreateReviewTest.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewServiceTest.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/dto/CreateReviewScheduleDtoBuilder.kt
domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/dto/UpdateReviewScheduleDtoBuilder.kt
helm_deploy/values-prod.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/DomainConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/inducton/PefInductionScheduleDateCalculationService.kt

This PR adds and optional env var to specify the date the Educational Contracts start and from which all schedule dates are based.
This should allow us to have the listeners etc running in prod from now, and also run the ETL in prod any time we like, and it will create "forward dated" Induction and Review schedules
The basic idea is that we set the env var in `prod` which sets the date that the new Education Contracts start (2025-04-01). This is an optional env var and is not set in other envs (though we could do if we wanted)
The date (if set) is injected into the 2 date calc classes (Induction & Review date calc classes), and is used as part of determining the deadline date for the schedule. IE. it uses the later of "today" or the injected date as the base date.
By not setting the env …

Optional env var to specify the date the Educational Contracts start

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/AuthAwareTokenConverter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/UserPrincipalAuditorAware.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/timeline/TimelineEventResourceMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/ManageUserService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/PrisonerApiTimelineService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/mapper/PrisonMovementEventsMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/UserPrincipalAuditorAwareTest.kt

This PR fixes the username that gets written to JPA fields via `UserPrincipalAuditorAware`, specifically in the case where the JWT is a system token and not one enriched with the DPS username

Fix username resolution in UserPrincipalAuditorAware

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ArchiveGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CompleteGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetConversationTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UnarchiveGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateConversationTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateEductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/JwtAccessTokenBuilder.kt

Final tidy up of displayName stuff - this PR removes the `displayName` argument from the functions in `JwtAccessTokenBuilder` (that build JWTs for the purpose of integration tests), and all places that used them

Remove displayName from JwtAccessTokenBuilder and all places that used it

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionSchedulePersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaReviewSchedulePersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InductionScheduleHistoryEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/review/ReviewScheduleHistoryEntity.kt

This PR fixes a problem when recording Induction Schedule History or Review Schedule History records, in that the  updatedAt dates do not get correctly updated, which is likely to cause MN a problem when we send them the history and they expect to sort them on updated date 🤣 
The problem (I suspect) is that in some cases (the status update methods) we were calling `save` rather than `saveAndFlush` on the Induction/Review Schedule entity classes, and I don't think JPA updates the audit fields via the entiry annotations until it flushes. Therefore, the first history record is correct, but when making a status update, the updatedAt date is copied from the original entity rather than the one that has been flushed with it's new updatedAt value.
I've also been explicit in the History entity …

Fix dates on InductionScheduleHistoryEntity and ReviewScheduleHistoryEntity

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/MonthsAndDaysLeftToServe.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleDateCalculationService.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleDateCalculationServiceTest.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleDateCalculationServiceWithEarliestScheduleDateTest.kt

This PR makes a minor fix to `ReviewScheduleDateCalculationService` to correctly calculate dates when the earliest date parameter is used in the constructor arg (ie. April 1st 2025 in our case); and writes specific tests all based on April 1st

RR-1238 - Fix date calculation tests for Review Schedules when a date offset is used

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleService.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleService.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerExemptDueToMergeEventTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundEventsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerMergedEventService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundEventsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerMergedEventServiceTest.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/AdditionalInformationBuilder.kt

Second PR for merge offender message processing. Here I'm checking to see if the person has a review or induction schedule then marking them as EXEMPT_PRISONER_MERGE. 
I wonder if we should also mark something else on the plp record to say that this person is removed due to merge? We don't store a prisoner record so maybe something on action plan?

merge offender

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleDateCalculationService.kt
domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleService.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleDateCalculationServiceTest.kt
domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleServiceTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedIntoPrisonEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ScheduleEtlController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/inducton/PefInductionScheduleDateCalculationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/inducton/PesInductionScheduleDateCalculationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedIntoPrisonEventServiceTest.kt

PR to address the following:
For prisoners who have a release date that falls prior to the deadline set on the 1st October 2025 then; 
We will set the deadline as their release date minus 7 days. This will reduce the risk of setting deadlines that are already overdue on go-live
If a prisoner is due to be released within 7 days of go live date (i.e. if they are released before 8 April) then they are exempt from the requirement

Specific rules for existing prisoners wrt induction deaslines

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/PrisonerSearchService.kt

Another temporary change to get round date conversion issues seen between local builds and cloud deployments surrounding the use of native query. This will almost certainly be replaced with a view and spring data repository methods in the near future and imminently if this iteration doesn't work.

date compatibility issue

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt

Due to the way the tests work the final three events have exactly the same timestamp:
1 EventType = ACTION_PLAN_CREATED time = 2025-03-11T09:58:42.820Z
2 EventType = GOAL_CREATED time = 2025-03-11T09:58:42.820Z
3 EventType = ACTION_PLAN_REVIEW_SCHEDULE_CREATED time = 2025-03-11T09:58:42.904Z
4 EventType = GOAL_UPDATED time = 2025-03-11T09:58:43.352Z
5 EventType = STEP_STARTED time = 2025-03-11T09:58:43.354Z
6 EventType = STEP_UPDATED time = 2025-03-11T09:58:43.354Z
When checking for the GOAL_UPDATED status this could be 4,5 or 6 
Have updated the test to be more lenient.

updated test

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt

Not 100% happy with this as it feels like a bit of a bodge.
Basically when we get the constraint issue - pause and then try again. I'm presuming that this is happening because the timeline records are still being written to the database asynchronously and some tests aren't using the await and check the timeline is complete - since they don't need to test this.

Handle DB constraint error

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerExemptDueToMergeEventTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedEventDueToTransferTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReleasedDueToDeathEventTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReleasedEventTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ArchiveGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CompleteGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanReviewTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateEducationTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalsTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanReviewsTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanSummariesTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetEducationTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetInductionScheduleTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetTimelineTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/SubjectAccessRequestTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UnarchiveGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateActionPlanReviewStatusHistoryTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateActionPlanReviewStatusTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateEductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionScheduleStatusTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ciag/GetCiagInductionSummariesTest.kt

The previous PR (where I repeated the database clear down twice when it failed) caused additional problems where it sometimes cleared the data for the next test that was running and caused that test to fail. 
Instead of clearing the data between each test I propose this PR where all integration tests use their own prisoner.
This means that we don't need to clear the database between each test. There are a couple of tests that still need to do this - they use a specific prisoner returned via Wiremock. For these tests I've added `@Isolated ` which should make them safe.

Changes to test resetting

---

src/main/resources/application.yml

fix to remove this warning 
HHH90000025: PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)

removed unnecessary config

---

domain/timeline/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/timeline/service/TimelineService.kt
domain/timeline/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/timeline/service/TimelineServiceFilterTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetTimelineTest.kt

Basically was trying to be too smart for my own good with the original version. The prisonId or eventsSince filters didn't work unless there was one of the boolean filters (goals, reviews etc) set.
Went back to the drawingboard and the process is now:
If eventSince is set then create a list of all events after that date otherwise include all. 
if prisonId is set then filter the previous list on prisonId
lastly apply the boolean filters. 
Also added specific tests for the conditions that were failing. 
This code can probably be refined further but I quite like the do this then this then this logic rather than some complex filters that can easily miss conditions if the testing isn't 100%.

Timeline filter fixes RR-1321 and RR-1322

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedDueToAdmissionEventTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedIntoPrisonEventService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedIntoPrisonEventServiceTest.kt

Create ReviewSchedule on prisoner admission when prisoner already has an Induction and Action Plan, but no InductionSchedule; IE. they are a re-offending prisoner who had a PLP and were released before 01/04/25, and re-offended and were re-admitted at some point after

RR-1397 - Create ReviewSchedule on prisoner admission when prisoner already has an Induction and Action Plan, but no InductionSchedule

---

helm_deploy/values-prod.yaml

PR to enable & configure the `postgresDatabaseRestore` job to perform a regular clone of the LWP `prod` database back to the `preprod` environment.

RR-1245 - Enable & configure postgresDatabaseRestore job

---

src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/actionplan/ArchiveGoalRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/actionplan/CompleteGoalRequestBuilder.kt
src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/actionplan/UnarchiveGoalRequestBuilder.kt

This PR updates the swagger spec to add the `prisonId` field to the request bodies for the API operations `archiveGoal`, `unarchiveGoal` and `completeGoal`.
Because the corresponding generated classes now have a new mandatory property (ie: `prisonId`), I've also had to update the test data builders for these classes.
All this PR does is introduce the new `prisonId` field to the request bodies. At the moment there is no further processing of these new properties, and any values passed by the client are essentially ignored (for now)
Subsequent PRs will implement the logic to update the `Goal` entity by setting the `updatedAtPrison` field with the passed `prisonId` value; but that can wait for now.

RR-1414 - Added prisonId to request body objects for archive, un-archive and complete goal APIs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonersearch/PrisonerSearchApiClient.kt

updated search API client to only return the fields we require: 
prisonerNumber
legalStatus,
releaseDate,
prisonId,
indeterminateSentence,
recall,
lastName,
firstName,
dateOfBirth,
cellLocation,
nonDtoReleaseDateType,

Updated search client to only return certain fields

---

domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/ArchiveGoalDto.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/CompleteGoalDto.kt
domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/UnarchiveGoalDto.kt
domain/personallearningplan/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/ArchiveGoalDtoBuilder.kt
domain/personallearningplan/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/UnarchiveGoalDtoBuilder.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ArchiveGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CompleteGoalTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UnarchiveGoalTest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/GoalResourceMapper.kt

Following the previous update to the API spec for archived/unarchived/completed goals, this PR sets the updated at prison when a goal is archived, unarchived or completed.

Set updated at prison when a goal is archived/unarchived/completed

---

helm_deploy/hmpps-education-and-work-plan-api/values.yaml
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/AssessmentEventProcessTest.kt
src/integrationTest/resources/application-integration-test.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundAssessmentEventsListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/SqsAssessmentEventMessage.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundAssessmentEventsListenerTest.kt

PR to process inbound assessment events from Meganexus. Currently only logs the message so the tests don't test anything except that the process doesn't fail. At least the framework is there for when we do add more functionality.

Initial PR to check wiring in dev

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ScheduleEtlController.kt

Probably won't need this one very often but this is an endpoint to generate induction schedule messages in the event we have to manually adjust data that has gone out of sync.

added message publisher for induction messages

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedIntoPrisonEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/ScheduleAdapter.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedIntoPrisonEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/validator/UpdateGoalRequestReferenceConstraintValidatorTest.kt

There have been numerous discrepancies found in the production data which suggest that we don't always get the inbound ADMISSION message. This means that we don't create the induction/review schedules for people that have previously been in LWP.  While that is a problem that needs solving there are some things we can do to prevent people from ending up in a stuck state. 
This PR will check the the presence of schedules when a goal is added - thus providing a way that users can unstuck a person. ie by creating a dummy goal. 
And also create schedules when a person is transferred - transfers happen frequently especially after a new admission. So if we don't get the message for a new admission then we will get one for a transfer.

Schedule adapter updates

---

helm_deploy/hmpps-education-and-work-plan-api/Chart.yaml

We had a critical alert from dependabot in the data extractor repository which required us to bump a few dependencies and create a new release. This PR bumps the data extractor to the latest release. We've tested this with the calculate-release-dates service and it worked without issue. Hope this is ok - happy to discuss. Thanks!

Update data extractor to latest

---

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleDateCalculationService.kt

Investigating a bug where a new review was generated even though the release date was in the next week. The review should have been completed and marked as pre_release = true rather than creating a new release with a due date of 1 year in the future. 
I think - although I can't confirm - that the release date was set after the review was complete. The calculation rule was set to INDETERMINATE_SENTENCE which can only happen when there is no release date. 
This PR adds more logging so that the next time this happens we can be sure if the release date was set or not.

added extra logging for when the person has no release date
