src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/Link.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/Timeline.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/TimelineEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/service/TimelinePersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/service/TimelinePersistenceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/service/TimelineService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/TimelineTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/timeline/service/TimelineServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/testfixtures/domain/timeline/TimeLineBuilder.kt
This PR adds the basic domain classes for Timeline, and also a basis domain service so as to start establishing our patterns in this respect
=> Added basic timeline domain classes and basis service

build.gradle.kts, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ActionPlanController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ControllerSecurityConstants.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/WebTestClientExtentions.kt
Roles added to controller endpoints, with basic preliminary support for integration tests (which we will build upon)
=> Roles added to controller endpoints

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/StepResourceMapper.kt, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/GoalResourceMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/StepResourceMapperTest.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/CreateGoalRequestBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/StepRequestBuilder.kt
Swagger definition for a new endpoint to edit a Goal.
This endpoint is an "all or nothing" type affair - the whole Goal needs to be provided, or any missing data (e.g. a single Step) will be removed.
=> RR-3 - Edit goal swagger spec

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GlobalExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/Exceptions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/ActionPlanService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalServiceTest.kt
This PR implements the scenario where the goal requested to be updated cannot be found for the specified prisoner; it returns a 404 in this case 👍
=> RR-3 (3) - Implement code to return 404 when goal is not found

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GlobalExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/validator/UpdateGoalRequestReferenceConstraintValidator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/validator/UpdateGoalRequestReferenceConstraintValidatorTest.kt
The PR adds further request validation (via a Constraint Validator) to the Update Goal request to ensure that the goal reference number in the request URI path is the same as the goal reference in the request body
=> RR-3 (4) - Constraint validator to validate goal reference

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/GoalServiceTest.kt
This PR wires everything together to enable Updating A Goal 🎉
=> RR-3 - Wired up Controller to Service to PersistenceAdapter

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetActionPlanTest.kt, src/integrationTest/resources/application-integration-test.yml, src/integrationTest/resources/db/h2/V2023.08.15.0001__add_action_plan_fields.sql, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/ActionPlan.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/service/ActionPlanService.kt, src/main/resources/application.yml, src/main/resources/db/postgres/V2023.08.15.0001__add_action_plan_fields.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanEntityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/ActionPlanEntityMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/ActionPlanTest.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/ActionPlanEntityBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/goal/ActionPlanBuilder.kt
This PR add `reference` and `reviewDate` to the `ActionPlan` domain, entity and DB table.
=> RR-229 - Add new fields to Action Plan

build.gradle.kts
Version bump of HMPPS gradle plugin and openapi generator to fix a couple of recent security vulnerabilities
=> Version bump of HMPPS gradle plugin and openapi generator 

src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
This PR adds the upcoming GET Timeline by prisonNumber to the swagger spec.
=> RR-319 - Swagger spec for GET Timeline

domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/FutureWorkInterests.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/InPrisonInterests.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/Induction.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/PersonalSkillsAndInterests.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/PreviousQualifications.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/PreviousTraining.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/PreviousWorkExperiences.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/WorkOnRelease.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/FutureWorkInterestsBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/InPrisonInterestsBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/InductionBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/PersonalSkillsAndInterestsBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/PreviousQualificationsBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/PreviousTrainingBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/PreviousWorkExperiencesBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/WorkOnReleaseBuilder.kt
A first iteration of a domain model for a CIAG induction. See some of the comments and kdoc to explain some of the decisions.
=> RR-421 - Domain model for a CIAG Induction

domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreateFutureWorkInterestsDto.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreateInPrisonInterestsDto.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreateInductionDto.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreatePersonalSkillsAndInterestsDto.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreatePreviousQualificationsDto.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreatePreviousTrainingDto.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreatePreviousWorkExperiencesDto.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreateWorkOnReleaseDto.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreateFutureWorkInterestsDtoBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreateInPrisonInterestsDtoBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreateInductionDtoBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreatePersonalSkillsAndInterestsDtoBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreatePreviousQualificationsDtoBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreatePreviousTrainingDtoBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreatePreviousWorkExperiencesDtoBuilder.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/dto/CreateWorkOnReleaseDtoBuilder.kt
DTOs for creating an Induction. Mappers etc to follow in separate PRs.
=> RR-424 Create Induction DTOs, plus builders

domain/induction/build.gradle.kts, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/Exceptions.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/InductionNotFoundException.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionPersistenceAdapter.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionService.kt, domain/induction/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionServiceTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapter.kt
This PR adds the ability to create an Induction via the `InductionService` and `InductionPersistenceAdapter`.
=> RR-425 - Create Induction - service layer

src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
This PR adds the create Induction endpoint to our swagger spec. To avoid breaking the CIAG UI, it's as close as possible to the existing version in the CIAG API: https://ciag-induction-api-dev.hmpps.service.justice.gov.uk/swagger-ui/index.html#/ciag-resource-controller/createOffenderProfile
The structure (e.g. names of fields) are identical, but I've removed quite a few fields, such as the "JPA" type ones where relevant - for example:
```
"modifiedBy": "string",
"modifiedDateTime": "2023-10-20T10:12:36.284Z",
"id": 0,
```
Here's how the endpoint looks in our Swagger:
And here's an example request:
```
{
"requestDTO": {
"prisonId": "string",
"prisonName": "string",
"hopingToGetWork": "YES",
"reasonToNotGetWorkOther": "string",
"abilityToWorkOther": "string",
"abilityToWork": [ …
```
=> RR-426 Create induction swagger spec

domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/InPrisonInterestsBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/CreateCiagInductionRequestDataBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/EducationAndQualificationsRequestBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousWorkRequestBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PrisonWorkAndEducationRequestBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/SkillsAndInterestsRequestBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/WorkInterestsBuilder.kt
This PR adds the required test data builders for creating a fully populated `CreateCiagInductionRequestData`.
=> RR-427 - Create Induction resource test data builders

src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/CiagInductionResponseBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/EducationAndQualificationsResponseBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousWorkResponseBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PrisonWorkAndEducationResponseBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/SkillsAndInterestsResponseBuilder.kt
This PR adds the required test data builders for a `CiagInductionResponse` and its internal classes.
=> RR-430 CiagInductionResponse response builders

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/FutureWorkInterestsEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InPrisonInterestsEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PersonalSkillsAndInterestsEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousQualificationsEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousWorkExperiencesEntityMapper.kt
This PR reduces duplication in the entity mappers and makes some improvements that I've explained in comments below.
=> RR-493 - Tidy up entity mappers

src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
Swagger spec for the `/ciag/induction/list` endpoint
=> RR-509 - Swagger spec for the `/ciag/induction/list` endpoint

domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/InductionSummary.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionPersistenceAdapter.kt, domain/induction/src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionService.kt, domain/induction/src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/service/InductionServiceTest.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/CommonBuilders.kt, domain/induction/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/domain/induction/InductionSummaryBuilder.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetInductionSummariesTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InductionSummaryProjection.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/actionplan/ActionPlanEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/repository/InductionRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/InductionController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/CiagInductionResponseMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionPersistenceAdapterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionEntityMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/CiagInductionResponseMapperTest.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InductionSummaryProjectionBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/CiagInductionSummaryListResponseAssert.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/CiagInductionSummaryResponseBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/GetCiagInductionSummariesRequestBuilder.kt
Looks a lot like our action plan summaries endpoint implementation 😁
=> RR-509 - Implementation of the `/ciag/induction/list` endpoint

helm_deploy/hmpps-education-and-work-plan-api/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml
PR to enable the CIAG data migration in all envs and also temporarily set the replica count to 1.
=> Enable migration and change replicaCount to 1 in all envs

helm_deploy/hmpps-education-and-work-plan-api/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml
Once we've run the migration in all envs, we should immediately merge this PR.
=> Disable migration and reset replica count in all envs

src/integrationTest/resources/application-integration-test.yml, src/main/resources/application.yml
For more information, refer to Vlad Mihalcea's answer here: https://stackoverflow.com/a/48222934
=> RR-529 Disable open session in view

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsAndTrainingResourceMapper.kt, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsAndTrainingResourceMapperTest.kt
This PR specifies a new endpoint to retrieve Inductions.
=> RR-520 Swagger spec for retrieving Inductions

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/FutureWorkInterestsEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InPrisonInterestsEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PersonalSkillsAndInterestsEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousQualificationsEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousTrainingEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/PreviousWorkExperiencesEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/WorkOnReleaseEntityMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionEntityMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdateFutureWorkInterestsEntityMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdateInPrisonInterestsEntityMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdatePersonalSkillsAndInterestsEntityMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdatePreviousQualificationsEntityMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdatePreviousTrainingEntityMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdatePreviousWorkExperiencesEntityMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/UpdateWorkOnReleaseEntityMapperTest.kt
This PR makes some minor improvements, without affecting any underlying functionality.
=> RR-522 - Minor improvements to update methods in entity mappers

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaTimelinePersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/InboundEventsListener.kt
This PR reduces the detail of logged objects to prevent risk of PII exposure
=> RR-534 - Reduced detail of logged objects to prevent risk of PII exposure

helm_deploy/hmpps-education-and-work-plan-api/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, src/integrationTest/resources/application-integration-test.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/PrisonApiException.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaTimelinePersistenceAdapter.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaTimelinePersistenceAdapterTest.kt
This PR adds a client class and config to call the prison-api, as well as some temporary code to check everything is setup correctly in dev.
Do not merge to dev until [HAAR-2221](https://dsdmoj.atlassian.net/browse/HAAR-2221) is done.
[HAAR-2221]: https://dsdmoj.atlassian.net/browse/HAAR-2221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RR-565 - Prison API client and config

README.md, helm_deploy/hmpps-education-and-work-plan-api/values.yaml, src/integrationTest/resources/application-integration-test.yml
A few bits of config I missed in my [previous PR](https://github.com/ministryofjustice/hmpps-education-and-work-plan-api/pull/248) when removing SQS concerns.
=> RR-641 Remove additional SQS config

helm_deploy/hmpps-education-and-work-plan-api/values.yaml
Reverts the temporary change made in my last PR: https://github.com/ministryofjustice/hmpps-education-and-work-plan-api/pull/254
=> RR-641 Remove legacy (incorrect) secrets

README.md
Small fix to Swagger api docs link
=> Fixed link to Swagger API docs

build.gradle.kts, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/SubjectAccessRequest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/SubjectAccessRequestTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/SubjectAccessRequestService.kt, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/SubjectAccessRequestServiceTest.kt
Adds support for SAR endpoint, enabling retrieval of goal and induction data.
=> RR-728: Adds SAR endpoint to retrieve PLP goal and induction data

docker-compose.yml, helm_deploy/hmpps-education-and-work-plan-api/values.yaml
Added additional role, `ROLE_EDUCATION_WORK_PLAN_VIEWER` for retrieval PLP SAR data
=> Add ROLE_EDUCATION_WORK_PLAN_VIEWER to SAR endpoint

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/Conversation.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/ConversationNotFoundException.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/ConversationNote.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/dto/CreateConversationDto.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/dto/CreateConversationNoteDto.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationEventService.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationPersistenceAdapter.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationServiceTest.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/ConversationBuilder.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/ConversationNoteBuilder.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/dto/CreateConversationDtoBuilder.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/dto/CreateConversationNoteDtoBuilder.kt
This PR introduces the new domain classes, service class and persistence layer adapter interface for "conversation" (which is how we are modelling the concept of "notes")
=> RR-719 - Introduced "conversation" domain classes and services

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/dto/UpdateConversationDto.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationEventService.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationPersistenceAdapter.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationServiceTest.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/dto/UpdateConversationDtoBuilder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaConversationPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/conversation/ConversationEntityMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaConversationPersistenceAdapterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/conversation/ConversationEntityMapperTest.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/conversation/ConversationEntityAssert.kt
This PR adds the DTO and domain service methods for updating a Conversation (ie. note)
=> RR-719 - Domain classes and methods for updating a Conversation

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateConversationTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ConversationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/conversation/ConversationsResourceMapper.kt, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/conversation/ConversationEntityAssert.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/conversation/CreateConversationRequestBuilder.kt
This PR sets up the Conversation controller and adds the implementation for the create Conversation endpoint.
=> RR-797: Create Conversation endpoint implementation

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/dto/UpdateConversationDto.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/dto/UpdateConversationDtoBuilder.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateConversationTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaConversationPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/conversation/ConversationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/conversation/ConversationEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ConversationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GlobalExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/conversation/ConversationsResourceMapper.kt, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/conversation/ConversationEntityAssert.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/conversation/UpdateConversationRequest.kt
Adds the implementation for the update conversation endpoint.
=> RR-797: Update conversation endpoint implementation

.circleci/config.yml, build.gradle.kts, domain/learningandworkprogress/build.gradle.kts, domain/personallearningplan/build.gradle.kts, domain/timeline/build.gradle.kts
- Updated uk.gov.justice.hmpps.gradle-spring-boot to v6
- Updated hmpps-kotlin-spring-boot-starter library to v1
=> RR-838: Update uk.gov.justice.hmpps.gradle-spring-boot to v6

.circleci/config.yml
Updates CircleCI HMPPS Orb version to v9 and replaces `integration-test-environment` executor in favour of `hmpps/java_postgres` executor
=> RR-842: Update CircleCI HMPPS Orb version

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/PagedResult.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/PrisonerConversationNotFoundException.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationPersistenceAdapter.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/conversation/service/ConversationServiceTest.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/PagedResultBuilder.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetConversationTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetConversationsTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateConversationTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaConversationPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/conversation/ConversationEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/repository/ConversationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ConversationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GlobalExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/conversation/ConversationsResourceMapper.kt, src/main/resources/db/migration/common/V2024.06.05.0001__conversation_prison_number_index.sql, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/conversation/ConversationEntityMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/conversation/ConversationResourceMapperTest.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/conversation/ConversationsResponseAssert.kt
Adds the implementation for the get conversations endpoint, including support for paging.
=> RR-797: Get prisoner conversations endpoint implementation

.github/CODEOWNERS, .gitignore
Add CODEOWNERS file with our team name so we're automatically added to PRs.
=> RR-851: Add CODEOWNERS file

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/dto/CreatePreviousWorkExperiencesDto.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/dto/UpdatePreviousWorkExperiencesDto.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/dto/PreviousWorkExperiencesDtoBuilder.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateInductionTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PreviousWorkExperiencesEntity.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/ApiResponseAssertions.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/CreatePreviousWorkExperiencesRequestBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/InductionResponseAssert.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousWorkExperiencesResponseAssert.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/PreviousWorkExperiencesResponseBuilder.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/UpdatePreviousWorkExperiencesRequestBuilder.kt
I should have written some integration tests in my first PR for this bugfix! 😬 
Turns out my previous "fix" didnt fix it at all !
Integration tests in this PR now prove the fix 😁
=> RR-865 - Mapped `hasWorkedBeforeNotRelevantReason` field through domain to database

domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/ArchiveGoalResult.kt, domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/GetGoalsDto.kt, domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/GetGoalsResult.kt, domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/dto/UnarchiveGoalResult.kt, domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalPersistenceAdapter.kt, domain/personallearningplan/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalService.kt, domain/personallearningplan/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/personallearningplan/service/GoalServiceTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetGoalsTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/GoalResourceMapper.kt, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaGoalPersistenceAdapterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/ActionPlanResourceMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/SubjectAccessRequestServiceTest.kt
New endpoint to get goals. Allows filtering on a single status or listing all goals
=> RR-826: Add get goals endpoint

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetGoalTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GoalController.kt, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
This PR adds the API endpoint to return a single goal identified by its goal reference and associated prisoner prison number
=> RR-881 - getGoal API endpoint

src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsResourceMapperTest.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/induction/CreatePreviousQualificationsRequestBuilder.kt
Swagger spec for new pre-prison-education API endpoints
=> RR-901 - Swagger spec for new pre-prison-education API endpoints

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/Exceptions.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/service/EducationPersistenceAdapter.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/service/EducationService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/service/EducationServiceTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetEducationTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/DomainConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaEducationPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/EducationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GlobalExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/education/EducationResourceMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaEducationPersistenceAdapterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/education/EducationResourceMapperTest.kt
PR to add the implementation of the `GET /person/{prisonNumber}/education` REST API endpoint, along with associated unit and integration tests
=> RR-901 - Controller and associated classes to implement GET education endpoint

helm_deploy/hmpps-education-and-work-plan-api/templates/queue-housekeeping-cronjob.yaml, helm_deploy/hmpps-education-and-work-plan-api/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
This PR fixes my previous attempt of overriding the cron schedule (which didnt work 😬 ), based on advice in [this slack conversation](https://mojdt.slack.com/archives/C69NWE339/p1724422098363079)
=> Fix housekeeping cron schedule in dev and preprod to allow for scheduled downtime

docker-compose.yml, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
Couple of small changes - 
1. updated swagger so that the try it now should work with a valid JWT
2. updated docker compose so that the missing prison api url is there for dev.
=> Small changes to make the build work

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/PreviousQualifications.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/PreviousQualificationsBuilder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/PreviousQualificationsEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/education/EducationResourceMapper.kt, src/main/resources/db/migration/common/V2024.09.10.0001__education_level_data_fix.sql
Please review/approve, but not to be merged until we've had the OK from Nicola Page re: making a change to production records in this way.
---
Spoke with Nicola 15:30 10/09/24 and agreed with her that we can make this change.
=> RR-944 - Data fix for education_level

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/service/EducationEventService.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/service/EducationPersistenceAdapter.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/service/EducationService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/education/service/EducationServiceTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateEductionTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaEducationPersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/EducationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/education/EducationResourceMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/QualificationsResourceMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncEducationEventService.kt, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaEducationPersistenceAdapterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/education/EducationResourceMapperTest.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/education/AchievedQualificationResponseAssert.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/resource/model/education/UpdateEducationRequestBuilder.kt
This PR implements the PUT API endpoint to allow the update of prisoner education records
=> RR-901 - Controller and associated classes to implement PUT education endpoint

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/Exceptions.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/InductionSchedule.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/dto/CreateInductionScheduleDto.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionSchedulePersistenceAdapter.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionServiceTest.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/InductionScheduleBuilder.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/dto/CreateInductionScheduleDtoBuilder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/DomainConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionSchedulePersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InductionScheduleEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionScheduleEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/repository/InductionScheduleRepository.kt, src/main/resources/db/migration/common/V2024.11.09.0003__add_induction_schedule_table.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionSchedulePersistenceAdapterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/induction/InductionScheduleEntityMapperTest.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/entity/induction/InductionScheduleEntityBuilder.kt
PR to add the induction_schedule table and associated domain and persistence code, which we'll be needing for KPI1
=> RR-981 - Added induction_schedule table and associated domain and persistence code

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/GoalNoteService.kt
Issue is that when an action plan is created that has multiple goals it sometimes fails in dev with a concurrent modification exception. I've added a test that should replicate the issue but unfortunately has not failed for me. 
Perceived wisdom from the internet says to copy the list before doing anything with it - so that is my proposed fix. Just a shame I can't be more confident with a test that reproduces the problem.
=> Fix for concurrent modification exeption

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/GoalNoteService.kt
I say potential fix but I was unable to actually reproduce this problem in dev.
=> Potential fix for concurrent modification exceptions

src/integrationTest/resources/simulations/__files/user-asmith_gen.json, src/integrationTest/resources/simulations/mappings/user.json, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/WorkOnReleaseResourceMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/WorkOnReleaseResourceMapperTest.kt
This PR changes `WorkOnReleaseResourceMapper` (one of the mappers used by `InductionResourceMapper`) to lookup and map the displayName fields from the user service
=> RR-1011 - Mapped displayName fields in WorkOnReleaseResourceMapper via user lookup

.trivyignore, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/CompletedReview.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/ReviewSchedule.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/ReviewScheduleNotFoundException.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewPersistenceAdapter.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewSchedulePersistenceAdapter.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewServiceTest.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/CompletedReviewBuilder.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/ReviewScheduleBuilder.kt
This PR introduces the basic domain and service classes to support the concept of a Review Schedule and a Completed Review
=> RR-1065 - Basic domain and service classes for ReviewSchedule and CompletedReview

src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
This PR defines the API endpoint in the swagger spec for submitting a prisoner's review:
=> RR-1088 - Swagger spec to define endpoint to submit a prisoner review

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanReviewTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ReviewController.kt
This PR fixes the response code for the create reviews endpoint from a 200 OK to 201 CREATED (as per the definition in the swagger spec)
=> RR-1088 - Correct the response code for creating reviews

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/education/EducationResourceMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/education/EducationResourceMapperTest.kt
PR to lookup the displayName fields for Education resources via the UserService
=> RR-996 - Lookup displayName fields via userService

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/ReviewScheduleHistory.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewSchedulePersistenceAdapter.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewService.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetReviewSchedulesTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaReviewSchedulePersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/review/ReviewScheduleEntityMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/repository/ReviewScheduleHistoryRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ReviewController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/review/ReviewScheduleHistoryResponseMapper.kt, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
endpoint that will return the review schedule history for a prison number sample response: 
[
{
"reference": "91130fff-d6ce-4ead-8461-1507140a2ae0",
"reviewDateFrom": "2024-11-11",
"reviewDateTo": "2025-01-11",
"status": "COMPLETED",
"calculationRule": "BETWEEN_12_AND_60_MONTHS_TO_SERVE",
"createdBy": "auser_gen",
"createdByDisplayName": "Albert User",
"createdAt": "2024-12-11T18:40:39.268Z",
"createdAtPrison": "BXI",
"updatedBy": "auser_gen",
"updatedByDisplayName": "Albert User",
"updatedAt": "2024-12-11T18:40:38.268Z",
"updatedAtPrison": "BXI",
"version": 4
},
{
"reference": "91130fff-d6ce-4ead-8461-1507140a2ae0",
"reviewDateFrom": "2024-11-11",
"reviewDateTo": "2025-01-11",
"status": "SCHEDULED",
"calculationRule": "BETWEEN_12_AND_60_MONTHS_TO_SERVE",
"createdBy": "auser_gen", …
=> Added review schedule history endpoint.

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/Exceptions.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewServiceCreateInitialReviewScheduleTest.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewServiceCreateReviewTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ActionPlanController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GlobalExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/InductionController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ReviewScheduleEtlController.kt
PR to include all sentence types in Review Schedule calculation
=> RR-1009 - Include all sentence types in Review Schedule calculation

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ReviewScheduleEtlController.kt
Small change to fix the ETL so it no longer filters out sentenced prisoners with no release date - we no longer need to do this as the service method does it better/properly
=> Small change to fix the ETL so it no longer filters out sentenced prisoners with no release date

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleService.kt
Fixed bug so that it's the greater of the existing deadline OR today + additional days.
=> update deadline data

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/IntegrationTestBase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ArchiveGoalTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CompleteGoalTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateActionPlanReviewTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateGoalsTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CreateInductionTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetGoalsTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UnarchiveGoalTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateActionPlanReviewStatusTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionScheduleStatusTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateInductionTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/InductionHistoryScheduleResourceMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/InductionScheduleResourceMapper.kt
Duplicate code removal.
Fix for unchecked cast code smell.
=> code tidy pr

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleService.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleServiceTest.kt, domain/learningandworkprogress/src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/InductionScheduleHistoryBuilder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/InductionScheduleController.kt
PR to move 2 Induction Schedule related functions from `InductionService` into `InductionScheduleService`
=> RR-1198 - Move 2 Induction Schedule functions to InductionScheduleService

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/SentenceType.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleService.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleServiceCreateInitialReviewScheduleTest.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleServiceTest.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewServiceCreateReviewTest.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewServiceTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/config/DomainConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ReviewScheduleEtlController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/ReviewScheduleAdapter.kt
This PR moves 2 more review schedule centric functions from ReviewService to ReviewScheduleService
=> RR-1198 - Move 2 more Review Schedule functions to ReviewScheduleService

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/CiagKpiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedIntoPrisonEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReleasedFromPrisonEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/ciagkpi/PefCiagKpiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/ciagkpi/PesCiagKpiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedIntoPrisonEventServiceTest.kt
Some more tidying and refactoring to move us in the right direction in respect of refactoring how and where the initial Induction Schedule is calculated and created.
=> RR-1198 - Initial skeleton refactoring of CiagKpiService

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/dto/UpdateInductionScheduleStatusDto.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleDateCalculationService.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleDateCalculationServiceTest.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleServiceTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaInductionSchedulePersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedIntoPrisonEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/InductionScheduleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/inducton/PefInductionScheduleDateCalculationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/inducton/PesInductionScheduleDateCalculationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedIntoPrisonEventServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/inducton/PefInductionScheduleDateCalculationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/inducton/PesInductionScheduleDateCalculationServiceTest.kt
Part two of adding prison id to induction schedule.
=> second commit for created/updated at prison

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ArchiveGoalTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/CompleteGoalTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetTimelineTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UnarchiveGoalTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/UpdateGoalTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncActionPlanEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TimelineEventFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AsyncActionPlanEventServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/TimelineEventFactoryTest.kt
=> create induction timeline entry when an action plan is created

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/induction/InductionScheduleResourceMapper.kt, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
This should be the last piece of work in our API to get the new fields over to meganexus via the integration API.
=> Added the extra fields to the induction schedule mapper

src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/SessionSummaryController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/validator/ValidatorConstants.kt
I needed to add this so that the swagger spec includes the new response model type
=> RR-1246 - Skeleton controller method

src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
=> api spec for session endpoint

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/ActionPlanResourceMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/StepResourceMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/mapper/actionplan/GoalEntityMapperUpdateEntityFromDtoTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/ActionPlanResourceMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/mapper/actionplan/StepResourceMapperTest.kt
=> Converted final mapper and remove mapstruct completely

docker-compose.yml, src/main/resources/static/openapi/EducationAndWorkPlanAPI.yml
Also fixed the docker files so the backend can run locally
=> potential integration api fix

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/PrisonerSearchTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonersearch/PagedPrisonerResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/repository/PersonSearchRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ControllerSecurityConstants.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/PrisonerSearchController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/PrisonerSearchService.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonersearch/PrisonerBuilder.kt
Search api that will return all prisoners for a prison and will paginate and sort only, 
There is no filtering at present. 
There is a basic test to prove it works.
=> early commit of search with paging and sorting

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/PrisonerSearchTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ControllerSecurityConstants.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/PrisonerSearchController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/PrisonerSearchService.kt, src/testFixtures/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/JwtAccessTokenBuilder.kt
Updated to use the correct preauthorize  roles on the endpoint
changed the sorting to do nulls last on asc 
added more tests
=> corrected endpoint role protection

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleDateCalculationService.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleDateCalculationService.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/induction/service/InductionScheduleDateCalculationServiceTest.kt, domain/learningandworkprogress/src/test/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleDateCalculationServiceTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/messaging/PrisonerReceivedEventDueToTransferTest.kt
correctly set deadlines for induction_schedules and review_schedules when a prisoner is transferred
=> correctly set deadlines for induction_schedules and review_schedules

src/main/resources/db/migration/common/V2025.06.30.0001__Review_schedule_constraint.sql
added constraint to guard against creating multiple SCHEDULED review schedules.
=> added unique constraint

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GetAssessmentsRequiredTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/client/prisonersearch/Exceptions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/GlobalExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AssessmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/service/AssessmentServiceTest.kt
Revise the logic of basic skills assessment's eligibility
=> ESWE-1338 Revise logic (education assessment eligibility)

domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewSchedulePersistenceAdapter.kt, domain/learningandworkprogress/src/main/kotlin/uk/gov/justice/digital/hmpps/domain/learningandworkprogress/review/service/ReviewScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/database/jpa/JpaReviewSchedulePersistenceAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/educationandworkplanapi/app/resource/ReviewRepairController.kt
After checking a lot of prisoners on my previous PR this one will now update the start date. Plan is to do the friendly prison examples first then verify with them that they look ok,.
=> Hidden endpoint to correct review schedule start dates
